#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BeanstalkManagersRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "BeanstalkManagersRuntime_structs.hpp"


namespace SDK
{

// Class BeanstalkManagersRuntime.BeanstalkAccountItemDefinitionOverrideManager
// 0x0080 (0x00A8 - 0x0028)
class UBeanstalkAccountItemDefinitionOverrideManager : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UBeanCosmeticsData>      BeanCosmetics;                                     // 0x0030(0x0020)(Edit, DisableEditOnInstance, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UBeanCosmeticsData*                     BeanCosmeticsDataCache;                            // 0x0050(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TMap<struct FPrimaryAssetId, struct FBeanstalkAccountItemDefinitionOverride> OverrideCache;                                     // 0x0058(0x0050)(Transient, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"BeanstalkAccountItemDefinitionOverrideManager">();
	}
	static class UBeanstalkAccountItemDefinitionOverrideManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBeanstalkAccountItemDefinitionOverrideManager>();
	}
};
static_assert(alignof(UBeanstalkAccountItemDefinitionOverrideManager) == 0x000008, "Wrong alignment on UBeanstalkAccountItemDefinitionOverrideManager");
static_assert(sizeof(UBeanstalkAccountItemDefinitionOverrideManager) == 0x0000A8, "Wrong size on UBeanstalkAccountItemDefinitionOverrideManager");
static_assert(offsetof(UBeanstalkAccountItemDefinitionOverrideManager, BeanCosmetics) == 0x000030, "Member 'UBeanstalkAccountItemDefinitionOverrideManager::BeanCosmetics' has a wrong offset!");
static_assert(offsetof(UBeanstalkAccountItemDefinitionOverrideManager, BeanCosmeticsDataCache) == 0x000050, "Member 'UBeanstalkAccountItemDefinitionOverrideManager::BeanCosmeticsDataCache' has a wrong offset!");
static_assert(offsetof(UBeanstalkAccountItemDefinitionOverrideManager, OverrideCache) == 0x000058, "Member 'UBeanstalkAccountItemDefinitionOverrideManager::OverrideCache' has a wrong offset!");

}

