#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CareerUI

#include "Basic.hpp"

#include "ModelViewViewModel_classes.hpp"
#include "FortniteGame_structs.hpp"
#include "Engine_classes.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class CareerUI.FortCareerChangeFlagModalItemVM
// 0x0050 (0x00B8 - 0x0068)
class UFortCareerChangeFlagModalItemVM final : public UMVVMViewModelBase
{
public:
	class FString                                 RegionId;                                          // 0x0068(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FText                                   RegionDisplayName;                                 // 0x0078(0x0010)(BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	TSoftObjectPtr<class UTexture2D>              RegionFlagAsset;                                   // 0x0088(0x0020)(BlueprintVisible, BlueprintReadOnly, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsCurrent;                                        // 0x00A8(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortCareerUIManager*                   CareerUIManager;                                   // 0x00B0(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void InitializeVM(const class FString& InRegionID, const class FString& InCurrentRegionId);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCareerChangeFlagModalItemVM">();
	}
	static class UFortCareerChangeFlagModalItemVM* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCareerChangeFlagModalItemVM>();
	}
};
static_assert(alignof(UFortCareerChangeFlagModalItemVM) == 0x000008, "Wrong alignment on UFortCareerChangeFlagModalItemVM");
static_assert(sizeof(UFortCareerChangeFlagModalItemVM) == 0x0000B8, "Wrong size on UFortCareerChangeFlagModalItemVM");
static_assert(offsetof(UFortCareerChangeFlagModalItemVM, RegionId) == 0x000068, "Member 'UFortCareerChangeFlagModalItemVM::RegionId' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalItemVM, RegionDisplayName) == 0x000078, "Member 'UFortCareerChangeFlagModalItemVM::RegionDisplayName' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalItemVM, RegionFlagAsset) == 0x000088, "Member 'UFortCareerChangeFlagModalItemVM::RegionFlagAsset' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalItemVM, bIsCurrent) == 0x0000A8, "Member 'UFortCareerChangeFlagModalItemVM::bIsCurrent' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalItemVM, CareerUIManager) == 0x0000B0, "Member 'UFortCareerChangeFlagModalItemVM::CareerUIManager' has a wrong offset!");

// Class CareerUI.FortCareerStatsScreenVM
// 0x0048 (0x00B0 - 0x0068)
class UFortCareerStatsScreenVM : public UMVVMViewModelBase
{
public:
	class FString                                 RegionId;                                          // 0x0068(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FText                                   RegionDisplayName;                                 // 0x0078(0x0010)(BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	TSoftObjectPtr<class UTexture2D>              RegionFlagAsset;                                   // 0x0088(0x0020)(BlueprintVisible, BlueprintReadOnly, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortCareerUIManager*                   CareerUIManager;                                   // 0x00A8(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void InitializeVM();
	void SetOnboardingSeen(const struct FGameplayTag& InOnboardingSeenId);
	void SetOtherAccountId(const struct FUniqueNetIdRepl& InAccountId);

	bool HasSeenOnboarding(const struct FGameplayTag& InOnboardingSeenId) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCareerStatsScreenVM">();
	}
	static class UFortCareerStatsScreenVM* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCareerStatsScreenVM>();
	}
};
static_assert(alignof(UFortCareerStatsScreenVM) == 0x000008, "Wrong alignment on UFortCareerStatsScreenVM");
static_assert(sizeof(UFortCareerStatsScreenVM) == 0x0000B0, "Wrong size on UFortCareerStatsScreenVM");
static_assert(offsetof(UFortCareerStatsScreenVM, RegionId) == 0x000068, "Member 'UFortCareerStatsScreenVM::RegionId' has a wrong offset!");
static_assert(offsetof(UFortCareerStatsScreenVM, RegionDisplayName) == 0x000078, "Member 'UFortCareerStatsScreenVM::RegionDisplayName' has a wrong offset!");
static_assert(offsetof(UFortCareerStatsScreenVM, RegionFlagAsset) == 0x000088, "Member 'UFortCareerStatsScreenVM::RegionFlagAsset' has a wrong offset!");
static_assert(offsetof(UFortCareerStatsScreenVM, CareerUIManager) == 0x0000A8, "Member 'UFortCareerStatsScreenVM::CareerUIManager' has a wrong offset!");

// Class CareerUI.FortCareerChangeFlagModalVM
// 0x0028 (0x00D8 - 0x00B0)
class UFortCareerChangeFlagModalVM final : public UFortCareerStatsScreenVM
{
public:
	TMulticastInlineDelegate<void(struct FFortCompetitiveIdentityInfo& NewFlagRegionInfo)> OnFlagChanged;                                     // 0x00B0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	int32                                         RegionLockDaysRemaining;                           // 0x00C0(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bAllowedToChangeFlag;                              // 0x00C4(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UFortCareerChangeFlagModalItemVM*> AvailableRegions;                                  // 0x00C8(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Protected, NativeAccessSpecifierProtected)

public:
	void ChangeFlag(const class FString& InRegion);

	int32 GetFlagChangeCooldownDays() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCareerChangeFlagModalVM">();
	}
	static class UFortCareerChangeFlagModalVM* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCareerChangeFlagModalVM>();
	}
};
static_assert(alignof(UFortCareerChangeFlagModalVM) == 0x000008, "Wrong alignment on UFortCareerChangeFlagModalVM");
static_assert(sizeof(UFortCareerChangeFlagModalVM) == 0x0000D8, "Wrong size on UFortCareerChangeFlagModalVM");
static_assert(offsetof(UFortCareerChangeFlagModalVM, OnFlagChanged) == 0x0000B0, "Member 'UFortCareerChangeFlagModalVM::OnFlagChanged' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalVM, RegionLockDaysRemaining) == 0x0000C0, "Member 'UFortCareerChangeFlagModalVM::RegionLockDaysRemaining' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalVM, bAllowedToChangeFlag) == 0x0000C4, "Member 'UFortCareerChangeFlagModalVM::bAllowedToChangeFlag' has a wrong offset!");
static_assert(offsetof(UFortCareerChangeFlagModalVM, AvailableRegions) == 0x0000C8, "Member 'UFortCareerChangeFlagModalVM::AvailableRegions' has a wrong offset!");

// Class CareerUI.FortCareerUIManager
// 0x0058 (0x0088 - 0x0030)
class UFortCareerUIManager final : public UEngineSubsystem
{
public:
	uint8                                         Pad_30[0x50];                                      // 0x0030(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortCareerChangeFlagModalVM*           ChangeFlagModalVM;                                 // 0x0080(0x0008)(ZeroConstructor, Transient, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	class UFortCareerChangeFlagModalVM* GetChangeFlagModalVM();
	void InitializeManager(const class UObject* WorldContextObject);
	void SetMainAccountId();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCareerUIManager">();
	}
	static class UFortCareerUIManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCareerUIManager>();
	}
};
static_assert(alignof(UFortCareerUIManager) == 0x000008, "Wrong alignment on UFortCareerUIManager");
static_assert(sizeof(UFortCareerUIManager) == 0x000088, "Wrong size on UFortCareerUIManager");
static_assert(offsetof(UFortCareerUIManager, ChangeFlagModalVM) == 0x000080, "Member 'UFortCareerUIManager::ChangeFlagModalVM' has a wrong offset!");

// Class CareerUI.FortUIGameFeatureAction_CompeteTab
// 0x0020 (0x0048 - 0x0028)
class UFortUIGameFeatureAction_CompeteTab final : public UFortUIGameFeatureAction
{
public:
	TSoftClassPtr<class UClass>                   CareerStatsScreenClass;                            // 0x0028(0x0020)(Edit, DisableEditOnInstance, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortUIGameFeatureAction_CompeteTab">();
	}
	static class UFortUIGameFeatureAction_CompeteTab* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortUIGameFeatureAction_CompeteTab>();
	}
};
static_assert(alignof(UFortUIGameFeatureAction_CompeteTab) == 0x000008, "Wrong alignment on UFortUIGameFeatureAction_CompeteTab");
static_assert(sizeof(UFortUIGameFeatureAction_CompeteTab) == 0x000048, "Wrong size on UFortUIGameFeatureAction_CompeteTab");
static_assert(offsetof(UFortUIGameFeatureAction_CompeteTab, CareerStatsScreenClass) == 0x000028, "Member 'UFortUIGameFeatureAction_CompeteTab::CareerStatsScreenClass' has a wrong offset!");

}

