#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CRD_CinematicSequence

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "CRD_CinematicSequence_structs.hpp"
#include "MovieScene_structs.hpp"


namespace SDK
{

// Class CRD_CinematicSequence.CinematicSequenceDeviceBase
// 0x00E0 (0x0CE0 - 0x0C00)
class ACinematicSequenceDeviceBase final : public ABuildingProp
{
public:
	uint8                                         Pad_C00[0x50];                                     // 0x0C00(0x0050)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSoftClassPath                         AISpawnerDeviceClassPath;                          // 0x0C50(0x0018)(Edit, ZeroConstructor, DisableEditOnInstance, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class ULevelSequence*                         Sequence;                                          // 0x0C68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class ALevelSequenceActor*                    LevelSequenceActor;                                // 0x0C70(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AFortPlayerController*                  InstigatingController;                             // 0x0C78(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         InstigatingTeam;                                   // 0x0C80(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C81[0x3];                                      // 0x0C81(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	uint8                                         bLoopPlayback : 1;                                 // 0x0C84(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, BlueprintVisible, SaveGame, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         bAutoPlay : 1;                                     // 0x0C84(0x0001)(BitIndex: 0x01, PropSize: 0x0001 (Edit, BlueprintVisible, SaveGame, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_C85[0x3];                                      // 0x0C85(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	ECinematicSequenceEnabledOnPhase              EnabledOnPhase;                                    // 0x0C88(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ECinematicSequenceVisibility                  Visibility;                                        // 0x0C89(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bLevelSequenceActorAlwaysRelevant;                 // 0x0C8A(0x0001)(Edit, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C8B[0x1];                                      // 0x0C8B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PlayRate;                                          // 0x0C8C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EMovieSceneCompletionModeOverride             FinishCompletionStateOverride;                     // 0x0C90(0x0001)(Edit, BlueprintVisible, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C91[0x4F];                                     // 0x0C91(0x004F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void GoToEndAndStop();
	void HandleSequencePlayerCreated(class ULevelSequencePlayer* Player);
	void OnSequenceFinished();
	void Pause();
	void Play();
	void PlayReverse();
	void SetPlaybackFrame(int32 Frame);
	void SetPlaybackTime(float time);
	void SetPlayRate(float PlayRate_0);
	void SetSequence(class ULevelSequence* Sequence_0);
	void Stop();

	int32 GetPlaybackFrame() const;
	float GetPlaybackTime() const;
	float GetPlayRate() const;
	class UMovieSceneSequencePlayer* GetSequencePlayer() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CinematicSequenceDeviceBase">();
	}
	static class ACinematicSequenceDeviceBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACinematicSequenceDeviceBase>();
	}
};
static_assert(alignof(ACinematicSequenceDeviceBase) == 0x000008, "Wrong alignment on ACinematicSequenceDeviceBase");
static_assert(sizeof(ACinematicSequenceDeviceBase) == 0x000CE0, "Wrong size on ACinematicSequenceDeviceBase");
static_assert(offsetof(ACinematicSequenceDeviceBase, AISpawnerDeviceClassPath) == 0x000C50, "Member 'ACinematicSequenceDeviceBase::AISpawnerDeviceClassPath' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, Sequence) == 0x000C68, "Member 'ACinematicSequenceDeviceBase::Sequence' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, LevelSequenceActor) == 0x000C70, "Member 'ACinematicSequenceDeviceBase::LevelSequenceActor' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, InstigatingController) == 0x000C78, "Member 'ACinematicSequenceDeviceBase::InstigatingController' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, InstigatingTeam) == 0x000C80, "Member 'ACinematicSequenceDeviceBase::InstigatingTeam' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, EnabledOnPhase) == 0x000C88, "Member 'ACinematicSequenceDeviceBase::EnabledOnPhase' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, Visibility) == 0x000C89, "Member 'ACinematicSequenceDeviceBase::Visibility' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, bLevelSequenceActorAlwaysRelevant) == 0x000C8A, "Member 'ACinematicSequenceDeviceBase::bLevelSequenceActorAlwaysRelevant' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, PlayRate) == 0x000C8C, "Member 'ACinematicSequenceDeviceBase::PlayRate' has a wrong offset!");
static_assert(offsetof(ACinematicSequenceDeviceBase, FinishCompletionStateOverride) == 0x000C90, "Member 'ACinematicSequenceDeviceBase::FinishCompletionStateOverride' has a wrong offset!");

}

