#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CRDPlayerTrackerUI

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class CRDPlayerTrackerUI.CRDPlayerTrackerWidget
// 0x0010 (0x0370 - 0x0360)
class UCRDPlayerTrackerWidget final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_360[0x10];                                     // 0x0360(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CRDPlayerTrackerWidget">();
	}
	static class UCRDPlayerTrackerWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCRDPlayerTrackerWidget>();
	}
};
static_assert(alignof(UCRDPlayerTrackerWidget) == 0x000008, "Wrong alignment on UCRDPlayerTrackerWidget");
static_assert(sizeof(UCRDPlayerTrackerWidget) == 0x000370, "Wrong size on UCRDPlayerTrackerWidget");

// Class CRDPlayerTrackerUI.CRDPlayerTrackerUIComponent
// 0x0008 (0x00C0 - 0x00B8)
class UCRDPlayerTrackerUIComponent final : public UActorComponent
{
public:
	class UCRDPlayerTrackerWidget*                SpawnedWidget;                                     // 0x00B8(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CRDPlayerTrackerUIComponent">();
	}
	static class UCRDPlayerTrackerUIComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCRDPlayerTrackerUIComponent>();
	}
};
static_assert(alignof(UCRDPlayerTrackerUIComponent) == 0x000008, "Wrong alignment on UCRDPlayerTrackerUIComponent");
static_assert(sizeof(UCRDPlayerTrackerUIComponent) == 0x0000C0, "Wrong size on UCRDPlayerTrackerUIComponent");
static_assert(offsetof(UCRDPlayerTrackerUIComponent, SpawnedWidget) == 0x0000B8, "Member 'UCRDPlayerTrackerUIComponent::SpawnedWidget' has a wrong offset!");

}

