#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DelMarTrackSelectorUI

#include "Basic.hpp"

#include "DelMarTrackSelectorUI_classes.hpp"


namespace SDK
{

// Function DelMarTrackSelectorUI.DelMarRankedViewModel.InitializeRankedViewModal
// (Final, RequiredAPI, Native, Public, BlueprintCallable)

void UDelMarRankedViewModel::InitializeRankedViewModal()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitializeRankedViewModal");

	UObject::ProcessEvent(Func, nullptr);
}

}

