#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FancyToastWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FancyToastWidget.FancyToastWidget_C
// 0x00A0 (0x03C0 - 0x0320)
class UFancyToastWidget_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetSwitcher*                        TypeWidgetSwitcher;                                // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TitleRegular;                                      // 0x0330(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Title;                                             // 0x0338(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               SpecialToast;                                      // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 SmallPreviewPortrait;                              // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               RegularToast;                                      // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       DescriptionRegular;                                // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Description;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Outro;                                             // 0x0370(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnFinishedToast;                                   // 0x0378(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TSoftObjectPtr<class UTexture2D>              Dev_TestImage;                                     // 0x0388(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnToastClicked;                                    // 0x03A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          DoNotUseTimerToDismiss;                            // 0x03B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void Clicked();
	void CompleteToast();
	void ExecuteUbergraph_FancyToastWidget(int32 EntryPoint);
	void On_Idle_Finished();
	void OnLoaded_9A8F5ACC4328AC430C10CEB22D17B3C8(class UObject* Loaded);
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnShowToast(const struct FFortToastDisplayInfo& DispalyInfo);
	void RemoveWidget();
	void SetAndShowText(const class FText& Text, class UCommonTextBlock* TextBlock);
	void ShowToast(const struct FFortToastDisplayInfo& DisplayInfo);
	void SimulateAthenaStoreToast();
	void Start_Toast_Animation();
	void WidgetAnimationEvt_Intro_K2Node_WidgetAnimationEvent_0();
	void WidgetAnimationEvt_Intro_K2Node_WidgetAnimationEvent_1();
	void WidgetAnimationEvt_Outro_K2Node_WidgetAnimationEvent_2();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FancyToastWidget_C">();
	}
	static class UFancyToastWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFancyToastWidget_C>();
	}
};
static_assert(alignof(UFancyToastWidget_C) == 0x000008, "Wrong alignment on UFancyToastWidget_C");
static_assert(sizeof(UFancyToastWidget_C) == 0x0003C0, "Wrong size on UFancyToastWidget_C");
static_assert(offsetof(UFancyToastWidget_C, UberGraphFrame) == 0x000320, "Member 'UFancyToastWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, TypeWidgetSwitcher) == 0x000328, "Member 'UFancyToastWidget_C::TypeWidgetSwitcher' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, TitleRegular) == 0x000330, "Member 'UFancyToastWidget_C::TitleRegular' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, Title) == 0x000338, "Member 'UFancyToastWidget_C::Title' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, SpecialToast) == 0x000340, "Member 'UFancyToastWidget_C::SpecialToast' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, SmallPreviewPortrait) == 0x000348, "Member 'UFancyToastWidget_C::SmallPreviewPortrait' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, RegularToast) == 0x000350, "Member 'UFancyToastWidget_C::RegularToast' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, DescriptionRegular) == 0x000358, "Member 'UFancyToastWidget_C::DescriptionRegular' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, Description) == 0x000360, "Member 'UFancyToastWidget_C::Description' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, Intro) == 0x000368, "Member 'UFancyToastWidget_C::Intro' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, Outro) == 0x000370, "Member 'UFancyToastWidget_C::Outro' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, OnFinishedToast) == 0x000378, "Member 'UFancyToastWidget_C::OnFinishedToast' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, Dev_TestImage) == 0x000388, "Member 'UFancyToastWidget_C::Dev_TestImage' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, OnToastClicked) == 0x0003A8, "Member 'UFancyToastWidget_C::OnToastClicked' has a wrong offset!");
static_assert(offsetof(UFancyToastWidget_C, DoNotUseTimerToDismiss) == 0x0003B8, "Member 'UFancyToastWidget_C::DoNotUseTimerToDismiss' has a wrong offset!");

}

