#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FirstPlaceHighlightActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FirstPlaceHighlightActor.FirstPlaceHighlightActor_C
// 0x0018 (0x02D8 - 0x02C0)
class AFirstPlaceHighlightActor_C final : public AFortSpectatorPlayerHighlighter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               FirstPlacePlayerMaterialInstance;                  // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BeingFollowedBySpectatorCamChanged(bool bInBeingFollowedBySpectatorCam);
	void ExecuteUbergraph_FirstPlaceHighlightActor(int32 EntryPoint);
	void FirstPlaceHighlightEnabledChanged(bool bInFirstPlaceHighlightEnabled);
	void PlayerTeamColorChanged(const struct FLinearColor& TeamColor);
	void ReceiveBeginPlay();
	void SpectatorCameraTypeChanged(ESpectatorCameraType NewCameraType);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FirstPlaceHighlightActor_C">();
	}
	static class AFirstPlaceHighlightActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFirstPlaceHighlightActor_C>();
	}
};
static_assert(alignof(AFirstPlaceHighlightActor_C) == 0x000008, "Wrong alignment on AFirstPlaceHighlightActor_C");
static_assert(sizeof(AFirstPlaceHighlightActor_C) == 0x0002D8, "Wrong size on AFirstPlaceHighlightActor_C");
static_assert(offsetof(AFirstPlaceHighlightActor_C, UberGraphFrame) == 0x0002C0, "Member 'AFirstPlaceHighlightActor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AFirstPlaceHighlightActor_C, StaticMesh) == 0x0002C8, "Member 'AFirstPlaceHighlightActor_C::StaticMesh' has a wrong offset!");
static_assert(offsetof(AFirstPlaceHighlightActor_C, FirstPlacePlayerMaterialInstance) == 0x0002D0, "Member 'AFirstPlaceHighlightActor_C::FirstPlacePlayerMaterialInstance' has a wrong offset!");

}

