#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FNE_ConversationRuntime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"
#include "LocalizableMessage_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class FNE_ConversationRuntime.ConversationEntityProxyActor
// 0x0058 (0x0300 - 0x02A8)
class AConversationEntityProxyActor final : public AActor
{
public:
	TArray<class AController*>                    ControllersInConversation;                         // 0x02A8(0x0010)(Net, ZeroConstructor, RepNotify, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	class USceneComponent*                        RootSceneComponent;                                // 0x02B8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortNonPlayerConversationParticipantComponent* NonPlayerConversationComponent;                    // 0x02C0(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FLocalizableMessage                    SpeakerName;                                       // 0x02C8(0x0030)(Net, RepNotify, Protected, NativeAccessSpecifierProtected)
	class UObject*                                CachedConversationEntityComponent;                 // 0x02F8(0x0008)(Net, ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnRep_ControllersInConversation();
	void OnRep_SpeakerName();
	void OnServerConversationEnded(class AActor* ParticipantActorPlayer);
	void OnServerConversationStarted(class AActor* ParticipantActorPlayer, const struct FGameplayTag& ParticipantID);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ConversationEntityProxyActor">();
	}
	static class AConversationEntityProxyActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AConversationEntityProxyActor>();
	}
};
static_assert(alignof(AConversationEntityProxyActor) == 0x000008, "Wrong alignment on AConversationEntityProxyActor");
static_assert(sizeof(AConversationEntityProxyActor) == 0x000300, "Wrong size on AConversationEntityProxyActor");
static_assert(offsetof(AConversationEntityProxyActor, ControllersInConversation) == 0x0002A8, "Member 'AConversationEntityProxyActor::ControllersInConversation' has a wrong offset!");
static_assert(offsetof(AConversationEntityProxyActor, RootSceneComponent) == 0x0002B8, "Member 'AConversationEntityProxyActor::RootSceneComponent' has a wrong offset!");
static_assert(offsetof(AConversationEntityProxyActor, NonPlayerConversationComponent) == 0x0002C0, "Member 'AConversationEntityProxyActor::NonPlayerConversationComponent' has a wrong offset!");
static_assert(offsetof(AConversationEntityProxyActor, SpeakerName) == 0x0002C8, "Member 'AConversationEntityProxyActor::SpeakerName' has a wrong offset!");
static_assert(offsetof(AConversationEntityProxyActor, CachedConversationEntityComponent) == 0x0002F8, "Member 'AConversationEntityProxyActor::CachedConversationEntityComponent' has a wrong offset!");

// Class FNE_ConversationRuntime.FNE_NonPlayerConversationParticipantComponent
// 0x0000 (0x0638 - 0x0638)
class UFNE_NonPlayerConversationParticipantComponent final : public UFortNonPlayerConversationParticipantComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FNE_NonPlayerConversationParticipantComponent">();
	}
	static class UFNE_NonPlayerConversationParticipantComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFNE_NonPlayerConversationParticipantComponent>();
	}
};
static_assert(alignof(UFNE_NonPlayerConversationParticipantComponent) == 0x000008, "Wrong alignment on UFNE_NonPlayerConversationParticipantComponent");
static_assert(sizeof(UFNE_NonPlayerConversationParticipantComponent) == 0x000638, "Wrong size on UFNE_NonPlayerConversationParticipantComponent");

}

