#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_ServiceStation_Heal

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GCNL_ServiceStation_Heal.GCNL_ServiceStation_Heal_C.ExecuteUbergraph_GCNL_ServiceStation_Heal
// 0x0168 (0x0168 - 0x0000)
struct GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Target;                               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0018(0x00D0)(ConstParm, ContainsInstancedReference)
	struct FGameplayCueNotify_SpawnResult         K2Node_Event_SpawnResults;                         // 0x00E8(0x0058)(ConstParm, ContainsInstancedReference)
	bool                                          CallFunc_ActorHasTag_ReturnValue;                  // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemComponent*                     CallFunc_Array_Get_Item;                           // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      K2Node_DynamicCast_AsNiagara_Particle_System_Component; // 0x0158(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal) == 0x000008, "Wrong alignment on GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal");
static_assert(sizeof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal) == 0x000168, "Wrong size on GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, EntryPoint) == 0x000000, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::EntryPoint' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, K2Node_Event_Target) == 0x000010, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::K2Node_Event_Target' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, K2Node_Event_Parameters) == 0x000018, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, K2Node_Event_SpawnResults) == 0x0000E8, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::K2Node_Event_SpawnResults' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, CallFunc_ActorHasTag_ReturnValue) == 0x000140, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::CallFunc_ActorHasTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, CallFunc_Array_Get_Item) == 0x000148, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, CallFunc_Array_Length_ReturnValue) == 0x000150, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, K2Node_DynamicCast_AsNiagara_Particle_System_Component) == 0x000158, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::K2Node_DynamicCast_AsNiagara_Particle_System_Component' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, K2Node_DynamicCast_bSuccess) == 0x000160, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal, CallFunc_Less_IntInt_ReturnValue) == 0x000161, "Member 'GCNL_ServiceStation_Heal_C_ExecuteUbergraph_GCNL_ServiceStation_Heal::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function GCNL_ServiceStation_Heal.GCNL_ServiceStation_Heal_C.OnLoopingStart
// 0x0130 (0x0130 - 0x0000)
struct GCNL_ServiceStation_Heal_C_OnLoopingStart final
{
public:
	class AActor*                                 Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	struct FGameplayCueNotify_SpawnResult         SpawnResults;                                      // 0x00D8(0x0058)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(GCNL_ServiceStation_Heal_C_OnLoopingStart) == 0x000008, "Wrong alignment on GCNL_ServiceStation_Heal_C_OnLoopingStart");
static_assert(sizeof(GCNL_ServiceStation_Heal_C_OnLoopingStart) == 0x000130, "Wrong size on GCNL_ServiceStation_Heal_C_OnLoopingStart");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_OnLoopingStart, Target) == 0x000000, "Member 'GCNL_ServiceStation_Heal_C_OnLoopingStart::Target' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_OnLoopingStart, Parameters) == 0x000008, "Member 'GCNL_ServiceStation_Heal_C_OnLoopingStart::Parameters' has a wrong offset!");
static_assert(offsetof(GCNL_ServiceStation_Heal_C_OnLoopingStart, SpawnResults) == 0x0000D8, "Member 'GCNL_ServiceStation_Heal_C_OnLoopingStart::SpawnResults' has a wrong offset!");

}

