#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IconTextButton

#include "Basic.hpp"

#include "Slate_structs.hpp"
#include "Engine_structs.hpp"
#include "CommonUILegacy_classes.hpp"
#include "SlateCore_structs.hpp"
#include "CommonInput_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass IconTextButton.IconTextButton_C
// 0x01A0 (0x16E0 - 0x1540)
class UIconTextButton_C : public UCommonButtonLegacy
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1540(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNamedSlot*                             RightExtraContentSlot;                             // 0x1548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LeftSideImage;                                     // 0x1550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_ButtonContent;                       // 0x1558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ContentBorder;                                     // 0x1560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       CenterButtonTextWidget;                            // 0x1568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   ButtonText;                                        // 0x1570(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FSlateBrush                            IconBrush;                                         // 0x1580(0x00B0)(Edit, BlueprintVisible, ExposeOnSpawn)
	class UClass*                                 ControllerInputStyle;                              // 0x1630(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UClass*                                 MouseKeyboardStyle;                                // 0x1638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          ContentAlignment;                                  // 0x1640(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bMouseKeyboardStyleSet;                            // 0x1641(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1642[0x6];                                     // 0x1642(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   OverrideButtonText;                                // 0x1648(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	ETextJustify                                  ButtonTextJustification;                           // 0x1658(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          bDisplayAllCaps;                                   // 0x1659(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_165A[0x6];                                     // 0x165A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        PressProgress;                                     // 0x1660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIgnoreInputActionWidgetText;                      // 0x1668(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1669[0x7];                                     // 0x1669(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool HasFocus)> FocusChangedEvent;                                 // 0x1670(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FSlateFontInfo                         Font;                                              // 0x1680(0x0058)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          UseLightInput;                                     // 0x16D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BindCommonInputSubsystem(bool bBind);
	void BndEvt__UI_BigGoldButton_InputActionWidget_K2Node_ComponentBoundEvent_0_OnInputIconUpdated__DelegateSignature();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_IconTextButton(int32 EntryPoint);
	void Get_Dynamic_Material(class UMaterialInstanceDynamic** Ret_Material);
	void GetPressProgress(double* Progress);
	void InitializeButton();
	void OnActionComplete();
	void OnActionProgress(float HeldPercent);
	void OnCurrentTextStyleChanged();
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void OnTriggeredInputActionChanged(const struct FDataTableRowHandle& NewTriggeredAction);
	void OnTriggeringInputActionChanged(const struct FDataTableRowHandle& NewTriggeredAction);
	void PreConstruct(bool IsDesignTime);
	void Set_Icon(const struct FSlateBrush& IconBrush_0);
	void Set_Text(const class FText& ButtonText_0);
	void SetContentAlignment(EHorizontalAlignment ContentAlignment_0);
	void SetControllerStyle(class UClass* ControllerInputStyle_0);
	void SetInitialMouseKeyboardStyle();
	void SetMouseKeyboardStyle(class UClass* ControllerInputStyle_0);
	void SetTabLabelInfo(const struct FFortTabButtonLabelInfo& TabLabelInfo);
	void SetTextInternal(const class FText& InButtonText);
	void ShowIcon(bool bShouldShow);
	void UpdateContentAlignment();
	void UpdateStyle(bool UsingGamepad);
	void UpdateText();
	void UpdateTextAndStyle(ECommonInputType InputType);
	void UpdateTextStyle();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IconTextButton_C">();
	}
	static class UIconTextButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIconTextButton_C>();
	}
};
static_assert(alignof(UIconTextButton_C) == 0x000010, "Wrong alignment on UIconTextButton_C");
static_assert(sizeof(UIconTextButton_C) == 0x0016E0, "Wrong size on UIconTextButton_C");
static_assert(offsetof(UIconTextButton_C, UberGraphFrame) == 0x001540, "Member 'UIconTextButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, RightExtraContentSlot) == 0x001548, "Member 'UIconTextButton_C::RightExtraContentSlot' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, LeftSideImage) == 0x001550, "Member 'UIconTextButton_C::LeftSideImage' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, HorizontalBox_ButtonContent) == 0x001558, "Member 'UIconTextButton_C::HorizontalBox_ButtonContent' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, ContentBorder) == 0x001560, "Member 'UIconTextButton_C::ContentBorder' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, CenterButtonTextWidget) == 0x001568, "Member 'UIconTextButton_C::CenterButtonTextWidget' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, ButtonText) == 0x001570, "Member 'UIconTextButton_C::ButtonText' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, IconBrush) == 0x001580, "Member 'UIconTextButton_C::IconBrush' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, ControllerInputStyle) == 0x001630, "Member 'UIconTextButton_C::ControllerInputStyle' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, MouseKeyboardStyle) == 0x001638, "Member 'UIconTextButton_C::MouseKeyboardStyle' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, ContentAlignment) == 0x001640, "Member 'UIconTextButton_C::ContentAlignment' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, bMouseKeyboardStyleSet) == 0x001641, "Member 'UIconTextButton_C::bMouseKeyboardStyleSet' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, OverrideButtonText) == 0x001648, "Member 'UIconTextButton_C::OverrideButtonText' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, ButtonTextJustification) == 0x001658, "Member 'UIconTextButton_C::ButtonTextJustification' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, bDisplayAllCaps) == 0x001659, "Member 'UIconTextButton_C::bDisplayAllCaps' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, PressProgress) == 0x001660, "Member 'UIconTextButton_C::PressProgress' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, bIgnoreInputActionWidgetText) == 0x001668, "Member 'UIconTextButton_C::bIgnoreInputActionWidgetText' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, FocusChangedEvent) == 0x001670, "Member 'UIconTextButton_C::FocusChangedEvent' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, Font) == 0x001680, "Member 'UIconTextButton_C::Font' has a wrong offset!");
static_assert(offsetof(UIconTextButton_C, UseLightInput) == 0x0016D8, "Member 'UIconTextButton_C::UseLightInput' has a wrong offset!");

}

