#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InputPromptManagerRuntime

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// Enum InputPromptManagerRuntime.EInputAliasInhibitorFlags
// NumValues: 0x0005
enum class EInputAliasInhibitorFlags : uint8
{
	None                                     = 0,
	RequiresTicking                          = 1,
	IsPending                                = 64,
	IsActivelyInhibiting                     = 128,
	Default                                  = 65,
};

// Enum InputPromptManagerRuntime.EAliasInhibitorBehaviorDependingOnPresenceOfASC
// NumValues: 0x0002
enum class EAliasInhibitorBehaviorDependingOnPresenceOfASC : uint8
{
	AlwaysInhibitWhenMissingASC              = 0,
	NeverInhibitWhenMissingASC               = 1,
};

// Enum InputPromptManagerRuntime.EAliasInhibitorBehaviorDependingOnPresenceOfAbility
// NumValues: 0x0002
enum class EAliasInhibitorBehaviorDependingOnPresenceOfAbility : uint8
{
	AlwaysInhibitWhenMissingAbility          = 0,
	NeverInhibitWhenMissingAbility           = 1,
};

// Enum InputPromptManagerRuntime.EAliasInhibitorBehaviorDependingOnAbilityBeingActivatable
// NumValues: 0x0002
enum class EAliasInhibitorBehaviorDependingOnAbilityBeingActivatable : uint8
{
	InhibitWhenAbilityCannotBeActivated      = 0,
	InhibitWhenAbilityCanBeActivated         = 1,
};

// ScriptStruct InputPromptManagerRuntime.InputPromptManager_IMCPushParams
// 0x000C (0x000C - 0x0000)
struct FInputPromptManager_IMCPushParams final
{
public:
	bool                                          bAutoCreateAliases;                                // 0x0000(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PriorityOfIMC;                                     // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AliasesPriority;                                   // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FInputPromptManager_IMCPushParams) == 0x000004, "Wrong alignment on FInputPromptManager_IMCPushParams");
static_assert(sizeof(FInputPromptManager_IMCPushParams) == 0x00000C, "Wrong size on FInputPromptManager_IMCPushParams");
static_assert(offsetof(FInputPromptManager_IMCPushParams, bAutoCreateAliases) == 0x000000, "Member 'FInputPromptManager_IMCPushParams::bAutoCreateAliases' has a wrong offset!");
static_assert(offsetof(FInputPromptManager_IMCPushParams, PriorityOfIMC) == 0x000004, "Member 'FInputPromptManager_IMCPushParams::PriorityOfIMC' has a wrong offset!");
static_assert(offsetof(FInputPromptManager_IMCPushParams, AliasesPriority) == 0x000008, "Member 'FInputPromptManager_IMCPushParams::AliasesPriority' has a wrong offset!");

// ScriptStruct InputPromptManagerRuntime.InputPromptManagerKnownListEntry
// 0x0010 (0x0010 - 0x0000)
struct FInputPromptManagerKnownListEntry final
{
public:
	class UInputAlias*                            KnownInputAlias;                                   // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInputPromptManagerKnownListEntry) == 0x000008, "Wrong alignment on FInputPromptManagerKnownListEntry");
static_assert(sizeof(FInputPromptManagerKnownListEntry) == 0x000010, "Wrong size on FInputPromptManagerKnownListEntry");
static_assert(offsetof(FInputPromptManagerKnownListEntry, KnownInputAlias) == 0x000000, "Member 'FInputPromptManagerKnownListEntry::KnownInputAlias' has a wrong offset!");

// ScriptStruct InputPromptManagerRuntime.LegacyInputBindingAliasData
// 0x0020 (0x0020 - 0x0000)
struct FLegacyInputBindingAliasData final
{
public:
	class FName                                   SpecializedActionName;                             // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   GeneralActionName;                                 // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ActionIdentifierName;                              // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ActionDescription;                                 // 0x0010(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
};
static_assert(alignof(FLegacyInputBindingAliasData) == 0x000008, "Wrong alignment on FLegacyInputBindingAliasData");
static_assert(sizeof(FLegacyInputBindingAliasData) == 0x000020, "Wrong size on FLegacyInputBindingAliasData");
static_assert(offsetof(FLegacyInputBindingAliasData, SpecializedActionName) == 0x000000, "Member 'FLegacyInputBindingAliasData::SpecializedActionName' has a wrong offset!");
static_assert(offsetof(FLegacyInputBindingAliasData, GeneralActionName) == 0x000004, "Member 'FLegacyInputBindingAliasData::GeneralActionName' has a wrong offset!");
static_assert(offsetof(FLegacyInputBindingAliasData, ActionIdentifierName) == 0x000008, "Member 'FLegacyInputBindingAliasData::ActionIdentifierName' has a wrong offset!");
static_assert(offsetof(FLegacyInputBindingAliasData, ActionDescription) == 0x000010, "Member 'FLegacyInputBindingAliasData::ActionDescription' has a wrong offset!");

// ScriptStruct InputPromptManagerRuntime.InputAliasInhibitor
// 0x0020 (0x0020 - 0x0000)
struct FInputAliasInhibitor
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 DevName;                                           // 0x0008(0x0010)(BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Flags;                                             // 0x0018(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInputAliasInhibitor) == 0x000008, "Wrong alignment on FInputAliasInhibitor");
static_assert(sizeof(FInputAliasInhibitor) == 0x000020, "Wrong size on FInputAliasInhibitor");
static_assert(offsetof(FInputAliasInhibitor, DevName) == 0x000008, "Member 'FInputAliasInhibitor::DevName' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor, Flags) == 0x000018, "Member 'FInputAliasInhibitor::Flags' has a wrong offset!");

// ScriptStruct InputPromptManagerRuntime.InputAliasInhibitor_AlwaysInhibit
// 0x0000 (0x0020 - 0x0020)
struct FInputAliasInhibitor_AlwaysInhibit final : public FInputAliasInhibitor
{
};
static_assert(alignof(FInputAliasInhibitor_AlwaysInhibit) == 0x000008, "Wrong alignment on FInputAliasInhibitor_AlwaysInhibit");
static_assert(sizeof(FInputAliasInhibitor_AlwaysInhibit) == 0x000020, "Wrong size on FInputAliasInhibitor_AlwaysInhibit");

// ScriptStruct InputPromptManagerRuntime.InputAliasInhibitor_AbilityActivation
// 0x0060 (0x0080 - 0x0020)
struct FInputAliasInhibitor_AbilityActivation final : public FInputAliasInhibitor
{
public:
	struct FGameplayAbilitySpecHandle             AbilityHandle;                                     // 0x0020(0x0004)(BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagQuery                      AbilityTagQuery;                                   // 0x0028(0x0048)(BlueprintVisible, NativeAccessSpecifierPublic)
	TSubclassOf<class UGameplayAbility>           AbilityClass;                                      // 0x0070(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAliasInhibitorBehaviorDependingOnPresenceOfASC BehaviorForASCAbsence;                             // 0x0078(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAliasInhibitorBehaviorDependingOnPresenceOfAbility BehaviorForAbilityAbsence;                         // 0x0079(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EAliasInhibitorBehaviorDependingOnAbilityBeingActivatable BehaviorBasedOnCanActivateAbility;                 // 0x007A(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7B[0x5];                                       // 0x007B(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FInputAliasInhibitor_AbilityActivation) == 0x000008, "Wrong alignment on FInputAliasInhibitor_AbilityActivation");
static_assert(sizeof(FInputAliasInhibitor_AbilityActivation) == 0x000080, "Wrong size on FInputAliasInhibitor_AbilityActivation");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, AbilityHandle) == 0x000020, "Member 'FInputAliasInhibitor_AbilityActivation::AbilityHandle' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, AbilityTagQuery) == 0x000028, "Member 'FInputAliasInhibitor_AbilityActivation::AbilityTagQuery' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, AbilityClass) == 0x000070, "Member 'FInputAliasInhibitor_AbilityActivation::AbilityClass' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, BehaviorForASCAbsence) == 0x000078, "Member 'FInputAliasInhibitor_AbilityActivation::BehaviorForASCAbsence' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, BehaviorForAbilityAbsence) == 0x000079, "Member 'FInputAliasInhibitor_AbilityActivation::BehaviorForAbilityAbsence' has a wrong offset!");
static_assert(offsetof(FInputAliasInhibitor_AbilityActivation, BehaviorBasedOnCanActivateAbility) == 0x00007A, "Member 'FInputAliasInhibitor_AbilityActivation::BehaviorBasedOnCanActivateAbility' has a wrong offset!");

}

