#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoCodexUI_CBC

#include "Basic.hpp"

#include "JunoCodexUI_CBC_classes.hpp"
#include "JunoCodexUI_CBC_parameters.hpp"


namespace SDK
{

// Function JunoCodexUI_CBC.JunoCodexItemComponentSlot.InitFromViewModel
// (Event, Public, BlueprintEvent)
// Parameters:
// class UJunoCraftingPartViewModel*       ViewModel                                              (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UJunoCodexItemComponentSlot::InitFromViewModel(const class UJunoCraftingPartViewModel* ViewModel)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("InitFromViewModel");

	Params::JunoCodexItemComponentSlot_InitFromViewModel Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}

}

