#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LiveEditObject

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "IrisCore_classes.hpp"
#include "LiveEditObject_structs.hpp"


namespace SDK
{

// Class LiveEditObject.LiveEditActorUtils
// 0x0000 (0x0028 - 0x0028)
class ULiveEditActorUtils final : public UBlueprintFunctionLibrary
{
public:
	static void ActorAttachmentChanged(class AActor* Actor, const class AActor* DefaultActor);
	static void ActorComponentCreated(class UActorComponent* Component, const class UActorComponent* SourceComponent);
	static void ActorComponentDestroyed(class UActorComponent* Component);
	static void ActorCreated(class AActor* Actor, const class AActor* SourceActor);
	static void ActorDestroyed(class AActor* Actor);
	static void ActorTransformChanged(class AActor* Actor, const class AActor* DefaultActor);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditActorUtils">();
	}
	static class ULiveEditActorUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditActorUtils>();
	}
};
static_assert(alignof(ULiveEditActorUtils) == 0x000008, "Wrong alignment on ULiveEditActorUtils");
static_assert(sizeof(ULiveEditActorUtils) == 0x000028, "Wrong size on ULiveEditActorUtils");

// Class LiveEditObject.LiveEditEntityUtils
// 0x0000 (0x0028 - 0x0028)
class ULiveEditEntityUtils final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditEntityUtils">();
	}
	static class ULiveEditEntityUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditEntityUtils>();
	}
};
static_assert(alignof(ULiveEditEntityUtils) == 0x000008, "Wrong alignment on ULiveEditEntityUtils");
static_assert(sizeof(ULiveEditEntityUtils) == 0x000028, "Wrong size on ULiveEditEntityUtils");

// Class LiveEditObject.LiveEditObjectInterface
// 0x0000 (0x0028 - 0x0028)
class ILiveEditObjectInterface final : public IInterface
{
public:
	void PushInitialStateToLiveEdit(const class UObject* DefaultObject);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectInterface">();
	}
	static class ILiveEditObjectInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<ILiveEditObjectInterface>();
	}
};
static_assert(alignof(ILiveEditObjectInterface) == 0x000008, "Wrong alignment on ILiveEditObjectInterface");
static_assert(sizeof(ILiveEditObjectInterface) == 0x000028, "Wrong size on ILiveEditObjectInterface");

// Class LiveEditObject.LiveEditObjectUtils
// 0x0000 (0x0028 - 0x0028)
class ULiveEditObjectUtils final : public UBlueprintFunctionLibrary
{
public:
	static void ObjectCreated(class UObject* Object, const class UObject* SourceObject);
	static void ObjectDestroyed(class UObject* Object);
	static void ObjectPropertiesChanged(const TArray<class FName>& Properties, class UObject* Object, const class UObject* DefaultObject);
	static void ObjectPropertyChanged(const class FName Property, class UObject* Object, const class UObject* DefaultObject);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectUtils">();
	}
	static class ULiveEditObjectUtils* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectUtils>();
	}
};
static_assert(alignof(ULiveEditObjectUtils) == 0x000008, "Wrong alignment on ULiveEditObjectUtils");
static_assert(sizeof(ULiveEditObjectUtils) == 0x000028, "Wrong size on ULiveEditObjectUtils");

// Class LiveEditObject.LiveEditNetworkStreamChannel
// 0x0000 (0x0068 - 0x0068)
class ULiveEditNetworkStreamChannel : public UChannel
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditNetworkStreamChannel">();
	}
	static class ULiveEditNetworkStreamChannel* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditNetworkStreamChannel>();
	}
};
static_assert(alignof(ULiveEditNetworkStreamChannel) == 0x000008, "Wrong alignment on ULiveEditNetworkStreamChannel");
static_assert(sizeof(ULiveEditNetworkStreamChannel) == 0x000068, "Wrong size on ULiveEditNetworkStreamChannel");

// Class LiveEditObject.LiveEditLargeNetworkMessageChannel
// 0x0048 (0x00B0 - 0x0068)
class ULiveEditLargeNetworkMessageChannel : public ULiveEditNetworkStreamChannel
{
public:
	uint8                                         Pad_68[0x48];                                      // 0x0068(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditLargeNetworkMessageChannel">();
	}
	static class ULiveEditLargeNetworkMessageChannel* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditLargeNetworkMessageChannel>();
	}
};
static_assert(alignof(ULiveEditLargeNetworkMessageChannel) == 0x000008, "Wrong alignment on ULiveEditLargeNetworkMessageChannel");
static_assert(sizeof(ULiveEditLargeNetworkMessageChannel) == 0x0000B0, "Wrong size on ULiveEditLargeNetworkMessageChannel");

// Class LiveEditObject.LiveEditObjectChannel
// 0x00F8 (0x01A8 - 0x00B0)
class ULiveEditObjectChannel final : public ULiveEditLargeNetworkMessageChannel
{
public:
	uint8                                         Pad_B0[0xF8];                                      // 0x00B0(0x00F8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectChannel">();
	}
	static class ULiveEditObjectChannel* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectChannel>();
	}
};
static_assert(alignof(ULiveEditObjectChannel) == 0x000008, "Wrong alignment on ULiveEditObjectChannel");
static_assert(sizeof(ULiveEditObjectChannel) == 0x0001A8, "Wrong size on ULiveEditObjectChannel");

// Class LiveEditObject.LiveEditObjectConnection
// 0x0348 (0x0370 - 0x0028)
class ULiveEditObjectConnection final : public UObject
{
public:
	uint8                                         Pad_28[0x348];                                     // 0x0028(0x0348)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectConnection">();
	}
	static class ULiveEditObjectConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectConnection>();
	}
};
static_assert(alignof(ULiveEditObjectConnection) == 0x000008, "Wrong alignment on ULiveEditObjectConnection");
static_assert(sizeof(ULiveEditObjectConnection) == 0x000370, "Wrong size on ULiveEditObjectConnection");

// Class LiveEditObject.LiveEditObjectDataStream
// 0x0050 (0x00B0 - 0x0060)
class ULiveEditObjectDataStream final : public UChunkedDataStream
{
public:
	uint8                                         Pad_60[0x50];                                      // 0x0060(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectDataStream">();
	}
	static class ULiveEditObjectDataStream* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectDataStream>();
	}
};
static_assert(alignof(ULiveEditObjectDataStream) == 0x000008, "Wrong alignment on ULiveEditObjectDataStream");
static_assert(sizeof(ULiveEditObjectDataStream) == 0x0000B0, "Wrong size on ULiveEditObjectDataStream");

// Class LiveEditObject.LiveEditObjectSubsystemState
// 0x0280 (0x02A8 - 0x0028)
class ULiveEditObjectSubsystemState final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ULiveEditObjectConnection*>      Connections;                                       // 0x0038(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8                                         Pad_48[0x260];                                     // 0x0048(0x0260)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectSubsystemState">();
	}
	static class ULiveEditObjectSubsystemState* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectSubsystemState>();
	}
};
static_assert(alignof(ULiveEditObjectSubsystemState) == 0x000008, "Wrong alignment on ULiveEditObjectSubsystemState");
static_assert(sizeof(ULiveEditObjectSubsystemState) == 0x0002A8, "Wrong size on ULiveEditObjectSubsystemState");
static_assert(offsetof(ULiveEditObjectSubsystemState, Connections) == 0x000038, "Member 'ULiveEditObjectSubsystemState::Connections' has a wrong offset!");

// Class LiveEditObject.LiveEditObjectSubsystem
// 0x0170 (0x01A0 - 0x0030)
class ULiveEditObjectSubsystem final : public UEngineSubsystem
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxBytesQueuedForReplication;                      // 0x0038(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	int32                                         NumPackageMapBunchesToDelayTickFor;                // 0x003C(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class ULiveEditObjectSubsystemState*>  NetDriverStates;                                   // 0x0040(0x0010)(ZeroConstructor, Transient, UObjectWrapper, NativeAccessSpecifierPrivate)
	uint8                                         Pad_50[0x150];                                     // 0x0050(0x0150)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectSubsystem">();
	}
	static class ULiveEditObjectSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectSubsystem>();
	}
};
static_assert(alignof(ULiveEditObjectSubsystem) == 0x000008, "Wrong alignment on ULiveEditObjectSubsystem");
static_assert(sizeof(ULiveEditObjectSubsystem) == 0x0001A0, "Wrong size on ULiveEditObjectSubsystem");
static_assert(offsetof(ULiveEditObjectSubsystem, MaxBytesQueuedForReplication) == 0x000038, "Member 'ULiveEditObjectSubsystem::MaxBytesQueuedForReplication' has a wrong offset!");
static_assert(offsetof(ULiveEditObjectSubsystem, NumPackageMapBunchesToDelayTickFor) == 0x00003C, "Member 'ULiveEditObjectSubsystem::NumPackageMapBunchesToDelayTickFor' has a wrong offset!");
static_assert(offsetof(ULiveEditObjectSubsystem, NetDriverStates) == 0x000040, "Member 'ULiveEditObjectSubsystem::NetDriverStates' has a wrong offset!");

// Class LiveEditObject.LiveEditObjectTestObject
// 0x0150 (0x0178 - 0x0028)
class ULiveEditObjectTestObject final : public UObject
{
public:
	int32                                         int32_0[0x3];                                      // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLiveEditObjectTestStruct              StructProperty;                                    // 0x0038(0x0140)(NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LiveEditObjectTestObject">();
	}
	static class ULiveEditObjectTestObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULiveEditObjectTestObject>();
	}
};
static_assert(alignof(ULiveEditObjectTestObject) == 0x000008, "Wrong alignment on ULiveEditObjectTestObject");
static_assert(sizeof(ULiveEditObjectTestObject) == 0x000178, "Wrong size on ULiveEditObjectTestObject");
static_assert(offsetof(ULiveEditObjectTestObject, int32_0) == 0x000028, "Member 'ULiveEditObjectTestObject::int32_0' has a wrong offset!");
static_assert(offsetof(ULiveEditObjectTestObject, StructProperty) == 0x000038, "Member 'ULiveEditObjectTestObject::StructProperty' has a wrong offset!");

}

