#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MatchmakingPortalUI

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CommonUI_classes.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class MatchmakingPortalUI.FortControllerComponent_CreativeMatchmaking
// 0x0100 (0x01C0 - 0x00C0)
class UFortControllerComponent_CreativeMatchmaking final : public UFortControllerComponent
{
public:
	class UFortGameActivity*                      CachedGameActivity;                                // 0x00C0(0x0008)(ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UFortCreativeMatchmakingFeedback> CreativeMatchmakingFeedbackClass;                  // 0x00C8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UFortActivityDetailsModal>  IslandModal;                                       // 0x00D0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortCreativeMatchmakingFeedback*       CreativeMatchmakingFeedbackWidget;                 // 0x00D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortActivityDetailsModal*              MatchmakingPortalModalWidget;                      // 0x00E0(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_E8[0xD8];                                      // 0x00E8(0x00D8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnCreativeReadyCheckStatusChanged(EInGameReadyCheckStatus InGameReadyCheckStatus);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortControllerComponent_CreativeMatchmaking">();
	}
	static class UFortControllerComponent_CreativeMatchmaking* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortControllerComponent_CreativeMatchmaking>();
	}
};
static_assert(alignof(UFortControllerComponent_CreativeMatchmaking) == 0x000008, "Wrong alignment on UFortControllerComponent_CreativeMatchmaking");
static_assert(sizeof(UFortControllerComponent_CreativeMatchmaking) == 0x0001C0, "Wrong size on UFortControllerComponent_CreativeMatchmaking");
static_assert(offsetof(UFortControllerComponent_CreativeMatchmaking, CachedGameActivity) == 0x0000C0, "Member 'UFortControllerComponent_CreativeMatchmaking::CachedGameActivity' has a wrong offset!");
static_assert(offsetof(UFortControllerComponent_CreativeMatchmaking, CreativeMatchmakingFeedbackClass) == 0x0000C8, "Member 'UFortControllerComponent_CreativeMatchmaking::CreativeMatchmakingFeedbackClass' has a wrong offset!");
static_assert(offsetof(UFortControllerComponent_CreativeMatchmaking, IslandModal) == 0x0000D0, "Member 'UFortControllerComponent_CreativeMatchmaking::IslandModal' has a wrong offset!");
static_assert(offsetof(UFortControllerComponent_CreativeMatchmaking, CreativeMatchmakingFeedbackWidget) == 0x0000D8, "Member 'UFortControllerComponent_CreativeMatchmaking::CreativeMatchmakingFeedbackWidget' has a wrong offset!");
static_assert(offsetof(UFortControllerComponent_CreativeMatchmaking, MatchmakingPortalModalWidget) == 0x0000E0, "Member 'UFortControllerComponent_CreativeMatchmaking::MatchmakingPortalModalWidget' has a wrong offset!");

// Class MatchmakingPortalUI.FortCreativeMatchmakingFeedback
// 0x0168 (0x05B8 - 0x0450)
class UFortCreativeMatchmakingFeedback final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_450[0x10];                                     // 0x0450(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortActivityScalingTextBlock*          Text_IslandName;                                   // 0x0460(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UFortActivityScalingTextBlock*          Text_MatchmakingStatus;                            // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_470[0x8];                                      // 0x0470(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bIsCancelingMatchmaking;                           // 0x0478(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bIsLocalPartyMemberReady;                          // 0x0479(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	bool                                          bHasPushedInputComponent;                          // 0x047A(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_47B[0x1D];                                     // 0x047B(0x001D)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGameActivity*                      CachedGameActivity;                                // 0x0498(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHasError;                                         // 0x04A0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4A1[0x7];                                      // 0x04A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   MatchmakingStatusText;                             // 0x04A8(0x0010)(BlueprintVisible, BlueprintReadOnly, Protected, NativeAccessSpecifierProtected)
	class UFortKeybindWidget*                     Action_HoldKeybindWidget;                          // 0x04B8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortCTAButton*                         Action_MobileButton;                               // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_4C8[0xF0];                                     // 0x04C8(0x00F0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BP_OnCreativeReadyCheckStatusChanged(EInGameReadyCheckStatus InGameReadyCheckStatus);
	void HandleCancelMatchmaking();
	void HoldAction();
	void HoldPressed();
	void HoldReleased();
	void OnCancelNotification();
	void OnCreativeReadyCheckStatusChanged(EInGameReadyCheckStatus InGameReadyCheckStatus);
	void OnLockStateChanged(bool bLockState);
	void OnMatchmakingStatusTextUpdated();
	void OnOutroFinished();
	void OnTakeActionNotification();
	void OnUserStartedHoldActionNotification();
	void PlayIntro();
	void PlayOutro();
	void PopInputComponent();
	void PushInputComponent();

	bool CanCancelMatchmaking() const;
	float GetTimeToDisplayMessageBeforeFadeOut() const;
	bool IsLocalPlayerReady() const;
	bool IsPartyLeader() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortCreativeMatchmakingFeedback">();
	}
	static class UFortCreativeMatchmakingFeedback* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortCreativeMatchmakingFeedback>();
	}
};
static_assert(alignof(UFortCreativeMatchmakingFeedback) == 0x000008, "Wrong alignment on UFortCreativeMatchmakingFeedback");
static_assert(sizeof(UFortCreativeMatchmakingFeedback) == 0x0005B8, "Wrong size on UFortCreativeMatchmakingFeedback");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, Text_IslandName) == 0x000460, "Member 'UFortCreativeMatchmakingFeedback::Text_IslandName' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, Text_MatchmakingStatus) == 0x000468, "Member 'UFortCreativeMatchmakingFeedback::Text_MatchmakingStatus' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, bIsCancelingMatchmaking) == 0x000478, "Member 'UFortCreativeMatchmakingFeedback::bIsCancelingMatchmaking' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, bIsLocalPartyMemberReady) == 0x000479, "Member 'UFortCreativeMatchmakingFeedback::bIsLocalPartyMemberReady' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, bHasPushedInputComponent) == 0x00047A, "Member 'UFortCreativeMatchmakingFeedback::bHasPushedInputComponent' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, CachedGameActivity) == 0x000498, "Member 'UFortCreativeMatchmakingFeedback::CachedGameActivity' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, bHasError) == 0x0004A0, "Member 'UFortCreativeMatchmakingFeedback::bHasError' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, MatchmakingStatusText) == 0x0004A8, "Member 'UFortCreativeMatchmakingFeedback::MatchmakingStatusText' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, Action_HoldKeybindWidget) == 0x0004B8, "Member 'UFortCreativeMatchmakingFeedback::Action_HoldKeybindWidget' has a wrong offset!");
static_assert(offsetof(UFortCreativeMatchmakingFeedback, Action_MobileButton) == 0x0004C0, "Member 'UFortCreativeMatchmakingFeedback::Action_MobileButton' has a wrong offset!");

// Class MatchmakingPortalUI.FortMatchmakingPortalCountdown
// 0x0030 (0x0480 - 0x0450)
class UFortMatchmakingPortalCountdown final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_450[0x8];                                      // 0x0450(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputComponent*                        MatchmakingPortalInputComponent;                   // 0x0458(0x0008)(ExportObject, ZeroConstructor, Transient, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UFortActivityScalingTextBlock*          Text_IslandName;                                   // 0x0460(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	float                                         CountdownTime;                                     // 0x0468(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_46C[0x4];                                      // 0x046C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnFinishedCountdown;                               // 0x0470(0x0010)(ZeroConstructor, InstancedReference, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void FinishTimer();
	void HandleCancelClicked();
	void StartCountdown();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortMatchmakingPortalCountdown">();
	}
	static class UFortMatchmakingPortalCountdown* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortMatchmakingPortalCountdown>();
	}
};
static_assert(alignof(UFortMatchmakingPortalCountdown) == 0x000008, "Wrong alignment on UFortMatchmakingPortalCountdown");
static_assert(sizeof(UFortMatchmakingPortalCountdown) == 0x000480, "Wrong size on UFortMatchmakingPortalCountdown");
static_assert(offsetof(UFortMatchmakingPortalCountdown, MatchmakingPortalInputComponent) == 0x000458, "Member 'UFortMatchmakingPortalCountdown::MatchmakingPortalInputComponent' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalCountdown, Text_IslandName) == 0x000460, "Member 'UFortMatchmakingPortalCountdown::Text_IslandName' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalCountdown, CountdownTime) == 0x000468, "Member 'UFortMatchmakingPortalCountdown::CountdownTime' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalCountdown, OnFinishedCountdown) == 0x000470, "Member 'UFortMatchmakingPortalCountdown::OnFinishedCountdown' has a wrong offset!");

// Class MatchmakingPortalUI.FortMatchmakingPortalPopup
// 0x0180 (0x05C8 - 0x0448)
class UFortMatchmakingPortalPopup final : public UFortPortalHUDDetails
{
public:
	uint8                                         Pad_448[0x10];                                     // 0x0448(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                WorldPointerLocation;                              // 0x0458(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FText                                   CreatorNameTextFormat;                             // 0x0470(0x0010)(Edit, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class UHeaderDescriptionHUDComponent> CachedHUDComponent;                                // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class UFortActivityDetailsModal>  IslandModal;                                       // 0x0488(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMatchmakingPortalPopupData            CachedIslandData;                                  // 0x0490(0x0048)(BlueprintVisible, Protected, NativeAccessSpecifierProtected)
	class FText                                   InvalidLinkCodeWarningText;                        // 0x04D8(0x0010)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	float                                         MatchmakingFeedbackDelayTime;                      // 0x04E8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         bIsWithinPortalRange : 1;                          // 0x04EC(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (BlueprintVisible, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected))
	uint8                                         Pad_4ED[0x3];                                      // 0x04ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonRichTextBlock*                   RichText_CreatorName;                              // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCommonTextBlock*                       Text_IslandName;                                   // 0x04F8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UDynamicEntryBox*                       EntryBox_ActivityTags;                             // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortKeybindWidget*                     GlobalActionKeybindWidget;                         // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UCommonActivatableWidget>   PlayerPageViewClass;                               // 0x0510(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UFortCampaignPurchaseScreen> ActivityCampaignPurchaseScreenClass;               // 0x0518(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class UFortActivityBrowserAttributionsModal> AttributionsModalClass;                            // 0x0520(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UFortGameActivity*                      CachedGameActivity;                                // 0x0528(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_530[0x10];                                     // 0x0530(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   InteractionMessage;                                // 0x0540(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class FText                                   InteractionMessage_Cancel;                         // 0x0550(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class FText                                   InteractionMessage_Disabled;                       // 0x0560(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	class FText                                   InteractionMessage_PartyLeadOnly;                  // 0x0570(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPrivate)
	uint8                                         Pad_580[0x48];                                     // 0x0580(0x0048)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BindOverlapEvents();
	bool GetIslandData(struct FMatchmakingPortalPopupData* OutIslandData, class UHeaderDescriptionHUDComponent* HUDComponent);
	void HandleHUDShow(const bool bShow, const bool bShouldAnimate);
	void HandleLoadScreenChanged(class AFortPlayerControllerAthena* PlayerController, bool bLoadScreenEnabled, const class FText& HUDReason);
	void HandleOnPortalDetailsVisibilityCheck(bool bShowWidget);
	void HandleStartedRespawn(class AFortPlayerControllerZone* PlayerController);
	void HandleWidgetUpdate();
	bool IsInteractingDeviceAMatchmakingPortal();
	void OnLockStateChanged();
	void OnPlayerCanInteractChanged(const bool bPlayerCanInteract, const class FText& Message);
	void OnShowPortalPopup(const bool bShow, const bool bAnimate);
	void UpdateVisuals(const class UHeaderDescriptionHUDComponent* HUDComponent);

	class UFortAthenaCreativeMatchmakingWidget* GetMatchmakingFeedbackWidget(const class UCommonActivatableWidget* MatchmakingFeedbackContainer) const;
	bool HasActivityToShow() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortMatchmakingPortalPopup">();
	}
	static class UFortMatchmakingPortalPopup* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortMatchmakingPortalPopup>();
	}
};
static_assert(alignof(UFortMatchmakingPortalPopup) == 0x000008, "Wrong alignment on UFortMatchmakingPortalPopup");
static_assert(sizeof(UFortMatchmakingPortalPopup) == 0x0005C8, "Wrong size on UFortMatchmakingPortalPopup");
static_assert(offsetof(UFortMatchmakingPortalPopup, WorldPointerLocation) == 0x000458, "Member 'UFortMatchmakingPortalPopup::WorldPointerLocation' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, CreatorNameTextFormat) == 0x000470, "Member 'UFortMatchmakingPortalPopup::CreatorNameTextFormat' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, CachedHUDComponent) == 0x000480, "Member 'UFortMatchmakingPortalPopup::CachedHUDComponent' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, IslandModal) == 0x000488, "Member 'UFortMatchmakingPortalPopup::IslandModal' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, CachedIslandData) == 0x000490, "Member 'UFortMatchmakingPortalPopup::CachedIslandData' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, InvalidLinkCodeWarningText) == 0x0004D8, "Member 'UFortMatchmakingPortalPopup::InvalidLinkCodeWarningText' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, MatchmakingFeedbackDelayTime) == 0x0004E8, "Member 'UFortMatchmakingPortalPopup::MatchmakingFeedbackDelayTime' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, RichText_CreatorName) == 0x0004F0, "Member 'UFortMatchmakingPortalPopup::RichText_CreatorName' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, Text_IslandName) == 0x0004F8, "Member 'UFortMatchmakingPortalPopup::Text_IslandName' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, EntryBox_ActivityTags) == 0x000500, "Member 'UFortMatchmakingPortalPopup::EntryBox_ActivityTags' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, GlobalActionKeybindWidget) == 0x000508, "Member 'UFortMatchmakingPortalPopup::GlobalActionKeybindWidget' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, PlayerPageViewClass) == 0x000510, "Member 'UFortMatchmakingPortalPopup::PlayerPageViewClass' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, ActivityCampaignPurchaseScreenClass) == 0x000518, "Member 'UFortMatchmakingPortalPopup::ActivityCampaignPurchaseScreenClass' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, AttributionsModalClass) == 0x000520, "Member 'UFortMatchmakingPortalPopup::AttributionsModalClass' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, CachedGameActivity) == 0x000528, "Member 'UFortMatchmakingPortalPopup::CachedGameActivity' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, InteractionMessage) == 0x000540, "Member 'UFortMatchmakingPortalPopup::InteractionMessage' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, InteractionMessage_Cancel) == 0x000550, "Member 'UFortMatchmakingPortalPopup::InteractionMessage_Cancel' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, InteractionMessage_Disabled) == 0x000560, "Member 'UFortMatchmakingPortalPopup::InteractionMessage_Disabled' has a wrong offset!");
static_assert(offsetof(UFortMatchmakingPortalPopup, InteractionMessage_PartyLeadOnly) == 0x000570, "Member 'UFortMatchmakingPortalPopup::InteractionMessage_PartyLeadOnly' has a wrong offset!");

// Class MatchmakingPortalUI.FortModalBackground
// 0x0038 (0x0488 - 0x0450)
class UFortModalBackground final : public UCommonActivatableWidget
{
public:
	uint8                                         Pad_450[0x20];                                     // 0x0450(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      Button_Back;                                       // 0x0470(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCommonButtonBase*                      Button_BackBoard;                                  // 0x0478(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UCommonButtonBase*                      Button_CloseTouch;                                 // 0x0480(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	void OnPreviewImageChanged(const bool bIsLoading, const class UTexture* InTexture);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortModalBackground">();
	}
	static class UFortModalBackground* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortModalBackground>();
	}
};
static_assert(alignof(UFortModalBackground) == 0x000008, "Wrong alignment on UFortModalBackground");
static_assert(sizeof(UFortModalBackground) == 0x000488, "Wrong size on UFortModalBackground");
static_assert(offsetof(UFortModalBackground, Button_Back) == 0x000470, "Member 'UFortModalBackground::Button_Back' has a wrong offset!");
static_assert(offsetof(UFortModalBackground, Button_BackBoard) == 0x000478, "Member 'UFortModalBackground::Button_BackBoard' has a wrong offset!");
static_assert(offsetof(UFortModalBackground, Button_CloseTouch) == 0x000480, "Member 'UFortModalBackground::Button_CloseTouch' has a wrong offset!");

// Class MatchmakingPortalUI.FortUIGameFeatureAction_OverridePortalHUDDetails
// 0x0020 (0x0048 - 0x0028)
class UFortUIGameFeatureAction_OverridePortalHUDDetails final : public UFortUIGameFeatureAction
{
public:
	TSoftClassPtr<class UClass>                   SoftPortalHUDDetailsClass;                         // 0x0028(0x0020)(Edit, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortUIGameFeatureAction_OverridePortalHUDDetails">();
	}
	static class UFortUIGameFeatureAction_OverridePortalHUDDetails* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortUIGameFeatureAction_OverridePortalHUDDetails>();
	}
};
static_assert(alignof(UFortUIGameFeatureAction_OverridePortalHUDDetails) == 0x000008, "Wrong alignment on UFortUIGameFeatureAction_OverridePortalHUDDetails");
static_assert(sizeof(UFortUIGameFeatureAction_OverridePortalHUDDetails) == 0x000048, "Wrong size on UFortUIGameFeatureAction_OverridePortalHUDDetails");
static_assert(offsetof(UFortUIGameFeatureAction_OverridePortalHUDDetails, SoftPortalHUDDetailsClass) == 0x000028, "Member 'UFortUIGameFeatureAction_OverridePortalHUDDetails::SoftPortalHUDDetailsClass' has a wrong offset!");

}

