#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MedallionUI

#include "Basic.hpp"

#include "MedallionUI_classes.hpp"
#include "MedallionUI_parameters.hpp"


namespace SDK
{

// Function MedallionUI.AthenaInventoryGroupMedallion.ShouldDisplayGroup
// (Event, Protected, BlueprintEvent, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UAthenaInventoryGroupMedallion::ShouldDisplayGroup() const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ShouldDisplayGroup");

	Params::AthenaInventoryGroupMedallion_ShouldDisplayGroup Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function MedallionUI.AthenaInventoryGroupMinorMedallion.BP_OnExtensionWidgetAdded
// (Event, Protected, BlueprintEvent)
// Parameters:
// EUIExtensionSlot                        ExtensionSlot                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUserWidget*                      ExtensionWidget                                        (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryGroupMinorMedallion::BP_OnExtensionWidgetAdded(EUIExtensionSlot ExtensionSlot, class UUserWidget* ExtensionWidget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnExtensionWidgetAdded");

	Params::AthenaInventoryGroupMinorMedallion_BP_OnExtensionWidgetAdded Parms{};

	Parms.ExtensionSlot = ExtensionSlot;
	Parms.ExtensionWidget = ExtensionWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MedallionUI.AthenaInventoryGroupMinorMedallion.BP_OnExtensionWidgetRemoved
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UUserWidget*                      ExtensionWidget                                        (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAthenaInventoryGroupMinorMedallion::BP_OnExtensionWidgetRemoved(class UUserWidget* ExtensionWidget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnExtensionWidgetRemoved");

	Params::AthenaInventoryGroupMinorMedallion_BP_OnExtensionWidgetRemoved Parms{};

	Parms.ExtensionWidget = ExtensionWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MedallionUI.MedallionsInfoWidget.HandleGameplayTagEvent
// (Final, Native, Protected)
// Parameters:
// struct FGameplayTag                     UpdatedTag                                             (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   TagCount                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UMedallionsInfoWidget::HandleGameplayTagEvent(const struct FGameplayTag& UpdatedTag, int32 TagCount)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleGameplayTagEvent");

	Params::MedallionsInfoWidget_HandleGameplayTagEvent Parms{};

	Parms.UpdatedTag = std::move(UpdatedTag);
	Parms.TagCount = TagCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MedallionUI.MedallionsInfoWidget.OnMedallionTagChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerStateAthena*           InPlayerState                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UMedallionsInfoWidget::OnMedallionTagChanged(class AFortPlayerStateAthena* InPlayerState)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMedallionTagChanged");

	Params::MedallionsInfoWidget_OnMedallionTagChanged Parms{};

	Parms.InPlayerState = InPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MedallionUI.MedallionsInfoWidget.OnPlayerDead
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerStateAthena*           PSA                                                    (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bIsDead                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UMedallionsInfoWidget::OnPlayerDead(class AFortPlayerStateAthena* PSA, bool bIsDead)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPlayerDead");

	Params::MedallionsInfoWidget_OnPlayerDead Parms{};

	Parms.PSA = PSA;
	Parms.bIsDead = bIsDead;

	UObject::ProcessEvent(Func, &Parms);
}

}

