#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MetaHumanUEFNRuntime

#include "Basic.hpp"

#include "GameFeatures_classes.hpp"
#include "MetaHumanSDKRuntime_structs.hpp"
#include "MetaHumanSDKRuntime_classes.hpp"


namespace SDK
{

// Class MetaHumanUEFNRuntime.GameFeatureAction_MetaHuman
// 0x0110 (0x0138 - 0x0028)
class UGameFeatureAction_MetaHuman final : public UGameFeatureAction
{
public:
	TMap<EMetaHumanBodyType, TSoftClassPtr<class UClass>> BodyPostAnimBPs;                                   // 0x0028(0x0050)(Edit, UObjectWrapper, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   Face_AnimBP;                                       // 0x0078(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   Face_PostAnimBP;                                   // 0x0098(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   BlendableBody_Face_PostAnimBP;                     // 0x00B8(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   RigidBodyAnimBP;                                   // 0x00D8(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   ControlRigRigidBodyAnimBP;                         // 0x00F8(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftClassPtr<class UClass>                   ControlRigAnimBP;                                  // 0x0118(0x0020)(Edit, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"GameFeatureAction_MetaHuman">();
	}
	static class UGameFeatureAction_MetaHuman* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameFeatureAction_MetaHuman>();
	}
};
static_assert(alignof(UGameFeatureAction_MetaHuman) == 0x000008, "Wrong alignment on UGameFeatureAction_MetaHuman");
static_assert(sizeof(UGameFeatureAction_MetaHuman) == 0x000138, "Wrong size on UGameFeatureAction_MetaHuman");
static_assert(offsetof(UGameFeatureAction_MetaHuman, BodyPostAnimBPs) == 0x000028, "Member 'UGameFeatureAction_MetaHuman::BodyPostAnimBPs' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, Face_AnimBP) == 0x000078, "Member 'UGameFeatureAction_MetaHuman::Face_AnimBP' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, Face_PostAnimBP) == 0x000098, "Member 'UGameFeatureAction_MetaHuman::Face_PostAnimBP' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, BlendableBody_Face_PostAnimBP) == 0x0000B8, "Member 'UGameFeatureAction_MetaHuman::BlendableBody_Face_PostAnimBP' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, RigidBodyAnimBP) == 0x0000D8, "Member 'UGameFeatureAction_MetaHuman::RigidBodyAnimBP' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, ControlRigRigidBodyAnimBP) == 0x0000F8, "Member 'UGameFeatureAction_MetaHuman::ControlRigRigidBodyAnimBP' has a wrong offset!");
static_assert(offsetof(UGameFeatureAction_MetaHuman, ControlRigAnimBP) == 0x000118, "Member 'UGameFeatureAction_MetaHuman::ControlRigAnimBP' has a wrong offset!");

// Class MetaHumanUEFNRuntime.MetaHumanComponent
// 0x0008 (0x0190 - 0x0188)
class UMetaHumanComponent final : public UMetaHumanComponentBase
{
public:
	int32                                         BodyLODThreshold;                                  // 0x0188(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MetaHumanComponent">();
	}
	static class UMetaHumanComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMetaHumanComponent>();
	}
};
static_assert(alignof(UMetaHumanComponent) == 0x000008, "Wrong alignment on UMetaHumanComponent");
static_assert(sizeof(UMetaHumanComponent) == 0x000190, "Wrong size on UMetaHumanComponent");
static_assert(offsetof(UMetaHumanComponent, BodyLODThreshold) == 0x000188, "Member 'UMetaHumanComponent::BodyLODThreshold' has a wrong offset!");

}

