#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MurkyVoleRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "FortniteGame_classes.hpp"
#include "MurkyVoleRuntime_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class MurkyVoleRuntime.FortControllerComponent_MurkyVole
// 0x0000 (0x00C0 - 0x00C0)
class UFortControllerComponent_MurkyVole final : public UFortControllerComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortControllerComponent_MurkyVole">();
	}
	static class UFortControllerComponent_MurkyVole* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortControllerComponent_MurkyVole>();
	}
};
static_assert(alignof(UFortControllerComponent_MurkyVole) == 0x000008, "Wrong alignment on UFortControllerComponent_MurkyVole");
static_assert(sizeof(UFortControllerComponent_MurkyVole) == 0x0000C0, "Wrong size on UFortControllerComponent_MurkyVole");

// Class MurkyVoleRuntime.FortGameplayAbility_MurkyVoleMissileManager
// 0x0008 (0x0C00 - 0x0BF8)
class UFortGameplayAbility_MurkyVoleMissileManager final : public UFortGameplayAbility_Action
{
public:
	class AFortWeaponRangedDual_MurkyVole*        CurrentWeapon;                                     // 0x0BF8(0x0008)(ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	bool CanFireMissile(const struct FMurkyVoleMissileSpawnInfo& SpawnInfo);
	void HandleMissileSpawned(class AFortProjectileBase* SpawnedProjectile);
	void ServerSpawnProjectile(const struct FMurkyVoleMissileSpawnInfo& SpawnInfo, const struct FPredictionKey& PredictionKey);
	void SpawnPredictiveMissileProjectile(const struct FMurkyVoleMissileSpawnInfo& SpawnInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortGameplayAbility_MurkyVoleMissileManager">();
	}
	static class UFortGameplayAbility_MurkyVoleMissileManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortGameplayAbility_MurkyVoleMissileManager>();
	}
};
static_assert(alignof(UFortGameplayAbility_MurkyVoleMissileManager) == 0x000008, "Wrong alignment on UFortGameplayAbility_MurkyVoleMissileManager");
static_assert(sizeof(UFortGameplayAbility_MurkyVoleMissileManager) == 0x000C00, "Wrong size on UFortGameplayAbility_MurkyVoleMissileManager");
static_assert(offsetof(UFortGameplayAbility_MurkyVoleMissileManager, CurrentWeapon) == 0x000BF8, "Member 'UFortGameplayAbility_MurkyVoleMissileManager::CurrentWeapon' has a wrong offset!");

// Class MurkyVoleRuntime.FortProjectileAthena_MurkyVole
// 0x0020 (0x0D10 - 0x0CF0)
class AFortProjectileAthena_MurkyVole final : public AFortProjectileAthena
{
public:
	uint8                                         Pad_CF0[0x20];                                     // 0x0CF0(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void TryToExplode(const bool bAllowOnServer);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortProjectileAthena_MurkyVole">();
	}
	static class AFortProjectileAthena_MurkyVole* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFortProjectileAthena_MurkyVole>();
	}
};
static_assert(alignof(AFortProjectileAthena_MurkyVole) == 0x000008, "Wrong alignment on AFortProjectileAthena_MurkyVole");
static_assert(sizeof(AFortProjectileAthena_MurkyVole) == 0x000D10, "Wrong size on AFortProjectileAthena_MurkyVole");

// Class MurkyVoleRuntime.FortProjectileMoveComp_DrunkMurkyVole
// 0x0470 (0x09B0 - 0x0540)
class UFortProjectileMoveComp_DrunkMurkyVole final : public UFortProjectileMoveComp_Drunk
{
public:
	struct FMurkyVoleDrunkProjectileConfig        NewDrunkConfig;                                    // 0x0538(0x0070)(BlueprintVisible, BlueprintReadOnly, Transient, NoDestructor, Protected, NativeAccessSpecifierProtected)
	bool                                          bKeepInitialSpeed;                                 // 0x05A8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_5A9[0x7];                                      // 0x05A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            DrunkSpeedScaleCurve;                              // 0x05B0(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UCurveFloat*                            DrunkGravityScaleCurve;                            // 0x05B8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MaxRandomTurnAngle;                                // 0x05C0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MinRandomTurnAngle;                                // 0x05E8(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DirectionChangeRate;                               // 0x0610(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         EnableAbovePlaneLimitation;                        // 0x0638(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         AbovePlaneDistanceThreshold;                       // 0x0660(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MaxAngleToLoseAbovePlaneLimit;                     // 0x0688(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MinAngleToLoseAbovePlaneLimit;                     // 0x06B0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         HomingRandomTargetPositionRadius;                  // 0x06D8(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         TargetedInitialDelay;                              // 0x0700(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DrunkVelocityInitialDelay;                         // 0x0728(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DrunkVelocityDuration;                             // 0x0750(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         bEnableDrunkTarget;                                // 0x0778(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DrunkTargetInitialDelay;                           // 0x07A0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DrunkTargetPositionLookaheadDist;                  // 0x07C8(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         StartBlendOutRange;                                // 0x07F0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         FinishBlendOutRange;                               // 0x0818(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         TimeThresholdForBlendOutOnTime;                    // 0x0840(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         BlendAlphaThresholdForBlendOutOnTime;              // 0x0868(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DurationForBlendOutOnTime;                         // 0x0890(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         HomingDrunkBlendOutTurnSpeed;                      // 0x08B8(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         TurnAngleBlendOutMultiplier;                       // 0x08E0(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DeviateStartAngle;                                 // 0x0908(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DeviateEndAngle;                                   // 0x0930(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DeviateMinBlendOutAlphaAddition;                   // 0x0958(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         DeviateMaxBlendOutAlphaAddition;                   // 0x0980(0x0028)(Edit, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_9A8[0x8];                                      // 0x09A8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetNewDrunkConfig(const struct FMurkyVoleDrunkProjectileConfig& NewConfig);

	const struct FMurkyVoleDrunkProjectileConfig GetDrunkConfig() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortProjectileMoveComp_DrunkMurkyVole">();
	}
	static class UFortProjectileMoveComp_DrunkMurkyVole* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortProjectileMoveComp_DrunkMurkyVole>();
	}
};
static_assert(alignof(UFortProjectileMoveComp_DrunkMurkyVole) == 0x000010, "Wrong alignment on UFortProjectileMoveComp_DrunkMurkyVole");
static_assert(sizeof(UFortProjectileMoveComp_DrunkMurkyVole) == 0x0009B0, "Wrong size on UFortProjectileMoveComp_DrunkMurkyVole");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, NewDrunkConfig) == 0x000538, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::NewDrunkConfig' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, bKeepInitialSpeed) == 0x0005A8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::bKeepInitialSpeed' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkSpeedScaleCurve) == 0x0005B0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkSpeedScaleCurve' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkGravityScaleCurve) == 0x0005B8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkGravityScaleCurve' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, MaxRandomTurnAngle) == 0x0005C0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::MaxRandomTurnAngle' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, MinRandomTurnAngle) == 0x0005E8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::MinRandomTurnAngle' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DirectionChangeRate) == 0x000610, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DirectionChangeRate' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, EnableAbovePlaneLimitation) == 0x000638, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::EnableAbovePlaneLimitation' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, AbovePlaneDistanceThreshold) == 0x000660, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::AbovePlaneDistanceThreshold' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, MaxAngleToLoseAbovePlaneLimit) == 0x000688, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::MaxAngleToLoseAbovePlaneLimit' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, MinAngleToLoseAbovePlaneLimit) == 0x0006B0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::MinAngleToLoseAbovePlaneLimit' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, HomingRandomTargetPositionRadius) == 0x0006D8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::HomingRandomTargetPositionRadius' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, TargetedInitialDelay) == 0x000700, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::TargetedInitialDelay' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkVelocityInitialDelay) == 0x000728, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkVelocityInitialDelay' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkVelocityDuration) == 0x000750, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkVelocityDuration' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, bEnableDrunkTarget) == 0x000778, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::bEnableDrunkTarget' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkTargetInitialDelay) == 0x0007A0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkTargetInitialDelay' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DrunkTargetPositionLookaheadDist) == 0x0007C8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DrunkTargetPositionLookaheadDist' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, StartBlendOutRange) == 0x0007F0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::StartBlendOutRange' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, FinishBlendOutRange) == 0x000818, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::FinishBlendOutRange' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, TimeThresholdForBlendOutOnTime) == 0x000840, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::TimeThresholdForBlendOutOnTime' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, BlendAlphaThresholdForBlendOutOnTime) == 0x000868, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::BlendAlphaThresholdForBlendOutOnTime' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DurationForBlendOutOnTime) == 0x000890, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DurationForBlendOutOnTime' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, HomingDrunkBlendOutTurnSpeed) == 0x0008B8, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::HomingDrunkBlendOutTurnSpeed' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, TurnAngleBlendOutMultiplier) == 0x0008E0, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::TurnAngleBlendOutMultiplier' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DeviateStartAngle) == 0x000908, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DeviateStartAngle' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DeviateEndAngle) == 0x000930, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DeviateEndAngle' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DeviateMinBlendOutAlphaAddition) == 0x000958, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DeviateMinBlendOutAlphaAddition' has a wrong offset!");
static_assert(offsetof(UFortProjectileMoveComp_DrunkMurkyVole, DeviateMaxBlendOutAlphaAddition) == 0x000980, "Member 'UFortProjectileMoveComp_DrunkMurkyVole::DeviateMaxBlendOutAlphaAddition' has a wrong offset!");

// Class MurkyVoleRuntime.FortWeaponRangedDual_MurkyVole
// 0x0100 (0x2718 - 0x2618)
class AFortWeaponRangedDual_MurkyVole final : public AFortWeaponRanged
{
public:
	TMulticastInlineDelegate<void(int32 OldMissileNumber)> OnMissileNumberChanged;                            // 0x2618(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UFortItemDefinition*                    MissileAmmoDefinition;                             // 0x2628(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSubclassOf<class AFortProjectileAthena>      MissileProjectileClass;                            // 0x2630(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MissileGravityScale;                               // 0x2638(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MissileMinTurnSpeed;                               // 0x2660(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MissileMaxTurnSpeed;                               // 0x2688(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MissileRampTimeForTurnSpeed;                       // 0x26B0(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         MissileLockTargetDistanceThreshold;                // 0x26D8(0x0028)(Edit, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	int32                                         MissileFiredNumber;                                // 0x2700(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         LocalMissileNumber;                                // 0x2704(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         ActualMissileNumber;                               // 0x2708(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, Transient, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_270C[0xC];                                     // 0x270C(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_MissileNumber(const int32 OldMissileNumber);

	void BPGetMuzzleBlockedLocation(bool* bMuzzleIsBlocked, struct FVector* MuzzleBlockedLocation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortWeaponRangedDual_MurkyVole">();
	}
	static class AFortWeaponRangedDual_MurkyVole* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFortWeaponRangedDual_MurkyVole>();
	}
};
static_assert(alignof(AFortWeaponRangedDual_MurkyVole) == 0x000008, "Wrong alignment on AFortWeaponRangedDual_MurkyVole");
static_assert(sizeof(AFortWeaponRangedDual_MurkyVole) == 0x002718, "Wrong size on AFortWeaponRangedDual_MurkyVole");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, OnMissileNumberChanged) == 0x002618, "Member 'AFortWeaponRangedDual_MurkyVole::OnMissileNumberChanged' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileAmmoDefinition) == 0x002628, "Member 'AFortWeaponRangedDual_MurkyVole::MissileAmmoDefinition' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileProjectileClass) == 0x002630, "Member 'AFortWeaponRangedDual_MurkyVole::MissileProjectileClass' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileGravityScale) == 0x002638, "Member 'AFortWeaponRangedDual_MurkyVole::MissileGravityScale' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileMinTurnSpeed) == 0x002660, "Member 'AFortWeaponRangedDual_MurkyVole::MissileMinTurnSpeed' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileMaxTurnSpeed) == 0x002688, "Member 'AFortWeaponRangedDual_MurkyVole::MissileMaxTurnSpeed' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileRampTimeForTurnSpeed) == 0x0026B0, "Member 'AFortWeaponRangedDual_MurkyVole::MissileRampTimeForTurnSpeed' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileLockTargetDistanceThreshold) == 0x0026D8, "Member 'AFortWeaponRangedDual_MurkyVole::MissileLockTargetDistanceThreshold' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, MissileFiredNumber) == 0x002700, "Member 'AFortWeaponRangedDual_MurkyVole::MissileFiredNumber' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, LocalMissileNumber) == 0x002704, "Member 'AFortWeaponRangedDual_MurkyVole::LocalMissileNumber' has a wrong offset!");
static_assert(offsetof(AFortWeaponRangedDual_MurkyVole, ActualMissileNumber) == 0x002708, "Member 'AFortWeaponRangedDual_MurkyVole::ActualMissileNumber' has a wrong offset!");

// Class MurkyVoleRuntime.MurkyVoleHoverLayerAnimInstance
// 0x0120 (0x1430 - 0x1310)
class UMurkyVoleHoverLayerAnimInstance final : public UFortPlayerAnimInstanceProxy
{
public:
	float                                         LeanX;                                             // 0x1308(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeanY;                                             // 0x130C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsHoverDash;                                      // 0x1310(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1311[0x3];                                     // 0x1311(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         HoverYawDelta;                                     // 0x1314(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DashX;                                             // 0x1318(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DashY;                                             // 0x131C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsHoverAddArms;                                   // 0x1320(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCanEnterPostBoost;                                // 0x1321(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1322[0x2];                                     // 0x1322(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           CooldownTagName;                                   // 0x1324(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         WeaponDisplayNameSubStringsToAddArmsAnim;          // 0x1328(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	TArray<class FString>                         WeaponDisplayNameSubStringsToAddArmsAnimWhenRelaxedLevel1; // 0x1338(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FCachedAnimRelevancyData               BoostToPostBoostRelevancyData;                     // 0x1348(0x0014)(Edit, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_135C[0xD4];                                    // 0x135C(0x00D4)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MurkyVoleHoverLayerAnimInstance">();
	}
	static class UMurkyVoleHoverLayerAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMurkyVoleHoverLayerAnimInstance>();
	}
};
static_assert(alignof(UMurkyVoleHoverLayerAnimInstance) == 0x000010, "Wrong alignment on UMurkyVoleHoverLayerAnimInstance");
static_assert(sizeof(UMurkyVoleHoverLayerAnimInstance) == 0x001430, "Wrong size on UMurkyVoleHoverLayerAnimInstance");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, LeanX) == 0x001308, "Member 'UMurkyVoleHoverLayerAnimInstance::LeanX' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, LeanY) == 0x00130C, "Member 'UMurkyVoleHoverLayerAnimInstance::LeanY' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, bIsHoverDash) == 0x001310, "Member 'UMurkyVoleHoverLayerAnimInstance::bIsHoverDash' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, HoverYawDelta) == 0x001314, "Member 'UMurkyVoleHoverLayerAnimInstance::HoverYawDelta' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, DashX) == 0x001318, "Member 'UMurkyVoleHoverLayerAnimInstance::DashX' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, DashY) == 0x00131C, "Member 'UMurkyVoleHoverLayerAnimInstance::DashY' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, bIsHoverAddArms) == 0x001320, "Member 'UMurkyVoleHoverLayerAnimInstance::bIsHoverAddArms' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, bCanEnterPostBoost) == 0x001321, "Member 'UMurkyVoleHoverLayerAnimInstance::bCanEnterPostBoost' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, CooldownTagName) == 0x001324, "Member 'UMurkyVoleHoverLayerAnimInstance::CooldownTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, WeaponDisplayNameSubStringsToAddArmsAnim) == 0x001328, "Member 'UMurkyVoleHoverLayerAnimInstance::WeaponDisplayNameSubStringsToAddArmsAnim' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, WeaponDisplayNameSubStringsToAddArmsAnimWhenRelaxedLevel1) == 0x001338, "Member 'UMurkyVoleHoverLayerAnimInstance::WeaponDisplayNameSubStringsToAddArmsAnimWhenRelaxedLevel1' has a wrong offset!");
static_assert(offsetof(UMurkyVoleHoverLayerAnimInstance, BoostToPostBoostRelevancyData) == 0x001348, "Member 'UMurkyVoleHoverLayerAnimInstance::BoostToPostBoostRelevancyData' has a wrong offset!");

// Class MurkyVoleRuntime.MurkyVolePackCCPAnimInstance
// 0x0170 (0x0910 - 0x07A0)
class UMurkyVolePackCCPAnimInstance final : public UCustomCharacterPartAnimInstance
{
public:
	bool                                          bHasHoverJets;                                     // 0x07A0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasMissileSwarm;                                  // 0x07A1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasTurret;                                        // 0x07A2(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsActiveMissileSwarm;                             // 0x07A3(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsActiveHover;                                    // 0x07A4(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7A5[0x3];                                      // 0x07A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LeanX;                                             // 0x07A8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LeanY;                                             // 0x07AC(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsHoverDash;                                      // 0x07B0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7B1[0x7];                                      // 0x07B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               AimRotationCurrent;                                // 0x07B8(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bIsWindUp;                                         // 0x07D0(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsWindDown;                                       // 0x07D1(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7D2[0x6];                                      // 0x07D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               PlayerAimRotation;                                 // 0x07D8(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               TurretAimRotation;                                 // 0x07F0(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               AdjustedRocketPodRot;                              // 0x0808(0x0018)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bIsTurretFire;                                     // 0x0820(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsTurretReFire;                                   // 0x0821(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_822[0x2];                                      // 0x0822(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TurretRailOffset;                                  // 0x0824(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsAutoTargetOff;                                  // 0x0828(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsAshtonShieldBlocking;                           // 0x0829(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsCrouchMoving;                                   // 0x082A(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsPawnSpeed2DAboveThreshold;                      // 0x082B(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TurretPitchOffset;                                 // 0x082C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           HoverJetsTagName;                                  // 0x0830(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           MissileSwarmTagName;                               // 0x0834(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           TurretTagName;                                     // 0x0838(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ActiveTagName;                                     // 0x083C(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           CooldownTagName;                                   // 0x0840(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ShotFiredTagName;                                  // 0x0844(0x0004)(Edit, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveTable*                            MurkyVoleGameplayGameDataCurveTable;               // 0x0848(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_850[0xC0];                                     // 0x0850(0x00C0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MurkyVolePackCCPAnimInstance">();
	}
	static class UMurkyVolePackCCPAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMurkyVolePackCCPAnimInstance>();
	}
};
static_assert(alignof(UMurkyVolePackCCPAnimInstance) == 0x000010, "Wrong alignment on UMurkyVolePackCCPAnimInstance");
static_assert(sizeof(UMurkyVolePackCCPAnimInstance) == 0x000910, "Wrong size on UMurkyVolePackCCPAnimInstance");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bHasHoverJets) == 0x0007A0, "Member 'UMurkyVolePackCCPAnimInstance::bHasHoverJets' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bHasMissileSwarm) == 0x0007A1, "Member 'UMurkyVolePackCCPAnimInstance::bHasMissileSwarm' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bHasTurret) == 0x0007A2, "Member 'UMurkyVolePackCCPAnimInstance::bHasTurret' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsActiveMissileSwarm) == 0x0007A3, "Member 'UMurkyVolePackCCPAnimInstance::bIsActiveMissileSwarm' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsActiveHover) == 0x0007A4, "Member 'UMurkyVolePackCCPAnimInstance::bIsActiveHover' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, LeanX) == 0x0007A8, "Member 'UMurkyVolePackCCPAnimInstance::LeanX' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, LeanY) == 0x0007AC, "Member 'UMurkyVolePackCCPAnimInstance::LeanY' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsHoverDash) == 0x0007B0, "Member 'UMurkyVolePackCCPAnimInstance::bIsHoverDash' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, AimRotationCurrent) == 0x0007B8, "Member 'UMurkyVolePackCCPAnimInstance::AimRotationCurrent' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsWindUp) == 0x0007D0, "Member 'UMurkyVolePackCCPAnimInstance::bIsWindUp' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsWindDown) == 0x0007D1, "Member 'UMurkyVolePackCCPAnimInstance::bIsWindDown' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, PlayerAimRotation) == 0x0007D8, "Member 'UMurkyVolePackCCPAnimInstance::PlayerAimRotation' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, TurretAimRotation) == 0x0007F0, "Member 'UMurkyVolePackCCPAnimInstance::TurretAimRotation' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, AdjustedRocketPodRot) == 0x000808, "Member 'UMurkyVolePackCCPAnimInstance::AdjustedRocketPodRot' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsTurretFire) == 0x000820, "Member 'UMurkyVolePackCCPAnimInstance::bIsTurretFire' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsTurretReFire) == 0x000821, "Member 'UMurkyVolePackCCPAnimInstance::bIsTurretReFire' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, TurretRailOffset) == 0x000824, "Member 'UMurkyVolePackCCPAnimInstance::TurretRailOffset' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsAutoTargetOff) == 0x000828, "Member 'UMurkyVolePackCCPAnimInstance::bIsAutoTargetOff' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsAshtonShieldBlocking) == 0x000829, "Member 'UMurkyVolePackCCPAnimInstance::bIsAshtonShieldBlocking' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsCrouchMoving) == 0x00082A, "Member 'UMurkyVolePackCCPAnimInstance::bIsCrouchMoving' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, bIsPawnSpeed2DAboveThreshold) == 0x00082B, "Member 'UMurkyVolePackCCPAnimInstance::bIsPawnSpeed2DAboveThreshold' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, TurretPitchOffset) == 0x00082C, "Member 'UMurkyVolePackCCPAnimInstance::TurretPitchOffset' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, HoverJetsTagName) == 0x000830, "Member 'UMurkyVolePackCCPAnimInstance::HoverJetsTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, MissileSwarmTagName) == 0x000834, "Member 'UMurkyVolePackCCPAnimInstance::MissileSwarmTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, TurretTagName) == 0x000838, "Member 'UMurkyVolePackCCPAnimInstance::TurretTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, ActiveTagName) == 0x00083C, "Member 'UMurkyVolePackCCPAnimInstance::ActiveTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, CooldownTagName) == 0x000840, "Member 'UMurkyVolePackCCPAnimInstance::CooldownTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, ShotFiredTagName) == 0x000844, "Member 'UMurkyVolePackCCPAnimInstance::ShotFiredTagName' has a wrong offset!");
static_assert(offsetof(UMurkyVolePackCCPAnimInstance, MurkyVoleGameplayGameDataCurveTable) == 0x000848, "Member 'UMurkyVolePackCCPAnimInstance::MurkyVoleGameplayGameDataCurveTable' has a wrong offset!");

// Class MurkyVoleRuntime.MurkyVoleTurretAttachment
// 0x02D0 (0x0578 - 0x02A8)
class AMurkyVoleTurretAttachment final : public AActor
{
public:
	TMap<struct FGameplayTag, struct FScalableFloat> PlayerPawnTargetTagToPctCapsuleHalfHeightZOffset;  // 0x02A8(0x0050)(BlueprintVisible, NativeAccessSpecifierPublic)
	TMap<struct FGameplayTag, struct FScalableFloat> NonPlayerPawnTargetTagToZOffsetMap;                // 0x02F8(0x0050)(BlueprintVisible, NativeAccessSpecifierPublic)
	struct FRotator                               AimRotation_Server;                                // 0x0348(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               AimRotation_Client;                                // 0x0360(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                TargetActorLastKnownLocation;                      // 0x0378(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ScannerRays_TargetingScale;                        // 0x0390(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Vector_AimSourceLocationOffset;                    // 0x03A8(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Vector_AimSourceLocationOffset_Crouch;             // 0x03C0(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FScalableFloat                         Row_PlayerPctCapsuleHalfHeightOffset_Default;      // 0x03D8(0x0028)(BlueprintVisible, NativeAccessSpecifierPublic)
	struct FScalableFloat                         Row_LaserMaxRange;                                 // 0x0400(0x0028)(BlueprintVisible, NativeAccessSpecifierPublic)
	struct FScalableFloat                         Row_LaserDistanceMulti;                            // 0x0428(0x0028)(BlueprintVisible, NativeAccessSpecifierPublic)
	double                                        ScannerRays_LastScaleUpdateTime;                   // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        ScannerRays_ScaleUpdateInterval;                   // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        ScannerRays_ScaleUpdateInterpSpeed;                // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 TargetActor;                                       // 0x0468(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceLaserOnWhileAttacking;                       // 0x0470(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTargetIsObstructed;                               // 0x0471(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_472[0x6E];                                     // 0x0472(0x006E)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           NativeCrouchTag;                                   // 0x04E0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FName                                   NativeBackpackAttachSocket;                        // 0x04E4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FScalableFloat                         NativePitchSpeed;                                  // 0x04E8(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	struct FScalableFloat                         NativeYawSpeed;                                    // 0x0510(0x0028)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	double                                        NativeBigPitchRangeMin;                            // 0x0538(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        NativeBigPitchRangeMax;                            // 0x0540(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        NativeBigYawRangeMin;                              // 0x0548(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        NativeBigYawRangeMax;                              // 0x0550(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        NativeSmallYawRangeMin;                            // 0x0558(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        NativeSmallYawRangeMax;                            // 0x0560(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NativeBigTimerRangeMin;                            // 0x0568(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NativeBigTimerRangeMax;                            // 0x056C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NativeSmallTimerRangeMin;                          // 0x0570(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         NativeSmallTimerRangeMax;                          // 0x0574(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void GetMuzzleSocketLocationAndRotation(struct FVector* SocketLocation, struct FRotator* SocketRotation);
	void GetTurretBlueprintData(class AActor** CurrentOwner, class UStaticMeshComponent** ScannerRays, class UStaticMeshComponent** IdleLaser, EMurkyVoleTurretState* CurrentState, struct FVector* BackpackMuzzleSocketLocation);
	void NativeForceLaserOnWhileAttacking(const class AActor* CurrentOwner, const EMurkyVoleTurretState CurrentState, class UStaticMeshComponent* ScannerRays, class UStaticMeshComponent* IdleLaser);
	void NativeGetAimSourceLocationForServer(const class AActor* CurrentOwner, const struct FVector& AimSourceLocationOffset, const struct FVector& AimSourceLocationOffsetCrouch, struct FVector* AimSourceLocation);
	void NativeGetLaserAimSourceLocationAndRotation(const class AActor* CurrentOwner, const class AFortPlayerController* LocalPlayerController, const struct FRotator& CalculatedAimRotation, struct FVector* AimSourceLocation, struct FRotator* AimSourceRotation);
	void NativeUpdateLaserLocationAndRotation(const class AActor* CurrentOwner, const class AFortPlayerController* LocalPlayerController, const struct FRotator& CalculatedAimRotation, class UStaticMeshComponent* Laser);
	void NativeUpdateLaserVisuals(const struct FMurkyVoleTurretAttachment_UpdateLaserVisualsParams& UpdateParams, const class AActor* CurrentOwner, class UStaticMeshComponent* ScannerRays, class UStaticMeshComponent* IdleLaser);
	void NativeUpdateRotation(const class AActor* CurrentOwner, const struct FRotator& ServerAimRotation, const struct FRotator& ClientAimRotation, const struct FVector& AimLocation, const struct FVector& AimSourceLocation, const bool bInTargetingState, struct FRotator* NewServerAimRotation, struct FRotator* NewClientAimRotation);
	void NativeUpdateTargetingLaserScale(const class AActor* CurrentOwner, const bool bSetMeshScale, const bool bCalculateNow, class UStaticMeshComponent* ScannerRays);
	void NativeUpdateTurret();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MurkyVoleTurretAttachment">();
	}
	static class AMurkyVoleTurretAttachment* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMurkyVoleTurretAttachment>();
	}
};
static_assert(alignof(AMurkyVoleTurretAttachment) == 0x000008, "Wrong alignment on AMurkyVoleTurretAttachment");
static_assert(sizeof(AMurkyVoleTurretAttachment) == 0x000578, "Wrong size on AMurkyVoleTurretAttachment");
static_assert(offsetof(AMurkyVoleTurretAttachment, PlayerPawnTargetTagToPctCapsuleHalfHeightZOffset) == 0x0002A8, "Member 'AMurkyVoleTurretAttachment::PlayerPawnTargetTagToPctCapsuleHalfHeightZOffset' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NonPlayerPawnTargetTagToZOffsetMap) == 0x0002F8, "Member 'AMurkyVoleTurretAttachment::NonPlayerPawnTargetTagToZOffsetMap' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, AimRotation_Server) == 0x000348, "Member 'AMurkyVoleTurretAttachment::AimRotation_Server' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, AimRotation_Client) == 0x000360, "Member 'AMurkyVoleTurretAttachment::AimRotation_Client' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, TargetActorLastKnownLocation) == 0x000378, "Member 'AMurkyVoleTurretAttachment::TargetActorLastKnownLocation' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, ScannerRays_TargetingScale) == 0x000390, "Member 'AMurkyVoleTurretAttachment::ScannerRays_TargetingScale' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, Vector_AimSourceLocationOffset) == 0x0003A8, "Member 'AMurkyVoleTurretAttachment::Vector_AimSourceLocationOffset' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, Vector_AimSourceLocationOffset_Crouch) == 0x0003C0, "Member 'AMurkyVoleTurretAttachment::Vector_AimSourceLocationOffset_Crouch' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, Row_PlayerPctCapsuleHalfHeightOffset_Default) == 0x0003D8, "Member 'AMurkyVoleTurretAttachment::Row_PlayerPctCapsuleHalfHeightOffset_Default' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, Row_LaserMaxRange) == 0x000400, "Member 'AMurkyVoleTurretAttachment::Row_LaserMaxRange' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, Row_LaserDistanceMulti) == 0x000428, "Member 'AMurkyVoleTurretAttachment::Row_LaserDistanceMulti' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, ScannerRays_LastScaleUpdateTime) == 0x000450, "Member 'AMurkyVoleTurretAttachment::ScannerRays_LastScaleUpdateTime' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, ScannerRays_ScaleUpdateInterval) == 0x000458, "Member 'AMurkyVoleTurretAttachment::ScannerRays_ScaleUpdateInterval' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, ScannerRays_ScaleUpdateInterpSpeed) == 0x000460, "Member 'AMurkyVoleTurretAttachment::ScannerRays_ScaleUpdateInterpSpeed' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, TargetActor) == 0x000468, "Member 'AMurkyVoleTurretAttachment::TargetActor' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, bForceLaserOnWhileAttacking) == 0x000470, "Member 'AMurkyVoleTurretAttachment::bForceLaserOnWhileAttacking' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, bTargetIsObstructed) == 0x000471, "Member 'AMurkyVoleTurretAttachment::bTargetIsObstructed' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeCrouchTag) == 0x0004E0, "Member 'AMurkyVoleTurretAttachment::NativeCrouchTag' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBackpackAttachSocket) == 0x0004E4, "Member 'AMurkyVoleTurretAttachment::NativeBackpackAttachSocket' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativePitchSpeed) == 0x0004E8, "Member 'AMurkyVoleTurretAttachment::NativePitchSpeed' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeYawSpeed) == 0x000510, "Member 'AMurkyVoleTurretAttachment::NativeYawSpeed' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigPitchRangeMin) == 0x000538, "Member 'AMurkyVoleTurretAttachment::NativeBigPitchRangeMin' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigPitchRangeMax) == 0x000540, "Member 'AMurkyVoleTurretAttachment::NativeBigPitchRangeMax' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigYawRangeMin) == 0x000548, "Member 'AMurkyVoleTurretAttachment::NativeBigYawRangeMin' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigYawRangeMax) == 0x000550, "Member 'AMurkyVoleTurretAttachment::NativeBigYawRangeMax' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeSmallYawRangeMin) == 0x000558, "Member 'AMurkyVoleTurretAttachment::NativeSmallYawRangeMin' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeSmallYawRangeMax) == 0x000560, "Member 'AMurkyVoleTurretAttachment::NativeSmallYawRangeMax' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigTimerRangeMin) == 0x000568, "Member 'AMurkyVoleTurretAttachment::NativeBigTimerRangeMin' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeBigTimerRangeMax) == 0x00056C, "Member 'AMurkyVoleTurretAttachment::NativeBigTimerRangeMax' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeSmallTimerRangeMin) == 0x000570, "Member 'AMurkyVoleTurretAttachment::NativeSmallTimerRangeMin' has a wrong offset!");
static_assert(offsetof(AMurkyVoleTurretAttachment, NativeSmallTimerRangeMax) == 0x000574, "Member 'AMurkyVoleTurretAttachment::NativeSmallTimerRangeMax' has a wrong offset!");

// Class MurkyVoleRuntime.MurkyVoleTurretAttachmentActorInterface
// 0x0000 (0x0028 - 0x0028)
class IMurkyVoleTurretAttachmentActorInterface final : public IInterface
{
public:
	void GetMurkyVoleTurretAttachmentData(bool* bIsInWindUpState, bool* bIsInWindDownState, bool* bIsInManualControlState, struct FRotator* AimRotationClient);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MurkyVoleTurretAttachmentActorInterface">();
	}
	static class IMurkyVoleTurretAttachmentActorInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IMurkyVoleTurretAttachmentActorInterface>();
	}
};
static_assert(alignof(IMurkyVoleTurretAttachmentActorInterface) == 0x000008, "Wrong alignment on IMurkyVoleTurretAttachmentActorInterface");
static_assert(sizeof(IMurkyVoleTurretAttachmentActorInterface) == 0x000028, "Wrong size on IMurkyVoleTurretAttachmentActorInterface");

}

