#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NoInputActionPipButton

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function NoInputActionPipButton.NoInputActionPipButton_C.ExecuteUbergraph_NoInputActionPipButton
// 0x0078 (0x0078 - 0x0000)
struct NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0008(0x0010)(HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimationForward_ReturnValue;         // 0x0018(0x0010)(HasGetValueTypeHash)
	class UFortRuntimeOptions*                    CallFunc_GetRuntimeOptions_ReturnValue;            // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Base_Color;                     // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Hover_Color;                    // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_Select_Color;                   // 0x0050(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62[0x6];                                       // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0072(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton) == 0x000008, "Wrong alignment on NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton");
static_assert(sizeof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton) == 0x000078, "Wrong size on NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, EntryPoint) == 0x000000, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_IsMobileGame_ReturnValue) == 0x000004, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000008, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_PlayAnimationForward_ReturnValue) == 0x000018, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_GetRuntimeOptions_ReturnValue) == 0x000028, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_GetRuntimeOptions_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, K2Node_CustomEvent_Base_Color) == 0x000030, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::K2Node_CustomEvent_Base_Color' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, K2Node_CustomEvent_Hover_Color) == 0x000040, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::K2Node_CustomEvent_Hover_Color' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, K2Node_CustomEvent_Select_Color) == 0x000050, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::K2Node_CustomEvent_Select_Color' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_BooleanAND_ReturnValue) == 0x000060, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, Temp_byte_Variable) == 0x000061, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000068, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, Temp_byte_Variable_1) == 0x000070, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, Temp_bool_Variable) == 0x000071, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton, K2Node_Select_Default) == 0x000072, "Member 'NoInputActionPipButton_C_ExecuteUbergraph_NoInputActionPipButton::K2Node_Select_Default' has a wrong offset!");

// Function NoInputActionPipButton.NoInputActionPipButton_C.Set Pip Colors
// 0x0030 (0x0030 - 0x0000)
struct NoInputActionPipButton_C_Set_Pip_Colors final
{
public:
	struct FLinearColor                           Base_Color;                                        // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Hover_Color;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Select_Color;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(NoInputActionPipButton_C_Set_Pip_Colors) == 0x000004, "Wrong alignment on NoInputActionPipButton_C_Set_Pip_Colors");
static_assert(sizeof(NoInputActionPipButton_C_Set_Pip_Colors) == 0x000030, "Wrong size on NoInputActionPipButton_C_Set_Pip_Colors");
static_assert(offsetof(NoInputActionPipButton_C_Set_Pip_Colors, Base_Color) == 0x000000, "Member 'NoInputActionPipButton_C_Set_Pip_Colors::Base_Color' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Set_Pip_Colors, Hover_Color) == 0x000010, "Member 'NoInputActionPipButton_C_Set_Pip_Colors::Hover_Color' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Set_Pip_Colors, Select_Color) == 0x000020, "Member 'NoInputActionPipButton_C_Set_Pip_Colors::Select_Color' has a wrong offset!");

// Function NoInputActionPipButton.NoInputActionPipButton_C.Set Selected
// 0x0028 (0x0028 - 0x0000)
struct NoInputActionPipButton_C_Set_Selected final
{
public:
	bool                                          Selected_0;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimationForward_ReturnValue;         // 0x0008(0x0010)(HasGetValueTypeHash)
	struct FWidgetAnimationHandle                 CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0018(0x0010)(HasGetValueTypeHash)
};
static_assert(alignof(NoInputActionPipButton_C_Set_Selected) == 0x000008, "Wrong alignment on NoInputActionPipButton_C_Set_Selected");
static_assert(sizeof(NoInputActionPipButton_C_Set_Selected) == 0x000028, "Wrong size on NoInputActionPipButton_C_Set_Selected");
static_assert(offsetof(NoInputActionPipButton_C_Set_Selected, Selected_0) == 0x000000, "Member 'NoInputActionPipButton_C_Set_Selected::Selected_0' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Set_Selected, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x000001, "Member 'NoInputActionPipButton_C_Set_Selected::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Set_Selected, CallFunc_PlayAnimationForward_ReturnValue) == 0x000008, "Member 'NoInputActionPipButton_C_Set_Selected::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Set_Selected, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000018, "Member 'NoInputActionPipButton_C_Set_Selected::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");

// Function NoInputActionPipButton.NoInputActionPipButton_C.Update Subscribed
// 0x0034 (0x0034 - 0x0000)
struct NoInputActionPipButton_C_Update_Subscribed final
{
public:
	bool                                          Subscribed;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue_1;                // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue_2;                // 0x0024(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(NoInputActionPipButton_C_Update_Subscribed) == 0x000004, "Wrong alignment on NoInputActionPipButton_C_Update_Subscribed");
static_assert(sizeof(NoInputActionPipButton_C_Update_Subscribed) == 0x000034, "Wrong size on NoInputActionPipButton_C_Update_Subscribed");
static_assert(offsetof(NoInputActionPipButton_C_Update_Subscribed, Subscribed) == 0x000000, "Member 'NoInputActionPipButton_C_Update_Subscribed::Subscribed' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Update_Subscribed, CallFunc_SelectColor_ReturnValue) == 0x000004, "Member 'NoInputActionPipButton_C_Update_Subscribed::CallFunc_SelectColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Update_Subscribed, CallFunc_SelectColor_ReturnValue_1) == 0x000014, "Member 'NoInputActionPipButton_C_Update_Subscribed::CallFunc_SelectColor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(NoInputActionPipButton_C_Update_Subscribed, CallFunc_SelectColor_ReturnValue_2) == 0x000024, "Member 'NoInputActionPipButton_C_Update_Subscribed::CallFunc_SelectColor_ReturnValue_2' has a wrong offset!");

}

