#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerDiscovered

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerDiscovered.PlayerDiscovered_C
// 0x00A0 (0x05D0 - 0x0530)
class UPlayerDiscovered_C final : public UAthenaDiscoveredAreaOverlay
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0530(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetSwitcher*                        WidgetSwitcher_LandmarkOrPOI;                      // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Underlay;                                  // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Container;                                 // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       MainLocationText_1;                                // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       MainLocationText;                                  // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           MainBox_Landmark;                                  // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           MainBox;                                           // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BulletRight;                                 // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BulletLeft;                                  // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       CommonTextBlock_LandmarkName;                      // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       BriefShow;                                         // 0x0588(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  RelevantPlaylistTags;                              // 0x0590(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	TSoftObjectPtr<class USoundCue>               SoundCue;                                          // 0x05B0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void BP_HandlePlaylistExtensionWidgetCreated(class UUserWidget* Widget, EUIExtensionSlot SlotType);
	void Brief_Show_Finished();
	void Construct();
	void EndOfShow();
	void ExecuteUbergraph_PlayerDiscovered(int32 EntryPoint);
	void K2_OnBecomeActive();
	void OnLoaded_A941D37E4EEBB55E1CF7C8B1203A946E(class UObject* Loaded);
	void OnNewDiscovery(const class FText& LocalizedLocationName, const TSoftObjectPtr<class USoundCue>& DiscoveredSoundCue, bool bIsNamedLocation, bool bIsDiscovered);
	void OnStompedByOtherWidget();
	void OnStompFailed();
	void Play_Brief_Show_Sound();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerDiscovered_C">();
	}
	static class UPlayerDiscovered_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerDiscovered_C>();
	}
};
static_assert(alignof(UPlayerDiscovered_C) == 0x000008, "Wrong alignment on UPlayerDiscovered_C");
static_assert(sizeof(UPlayerDiscovered_C) == 0x0005D0, "Wrong size on UPlayerDiscovered_C");
static_assert(offsetof(UPlayerDiscovered_C, UberGraphFrame) == 0x000530, "Member 'UPlayerDiscovered_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, WidgetSwitcher_LandmarkOrPOI) == 0x000538, "Member 'UPlayerDiscovered_C::WidgetSwitcher_LandmarkOrPOI' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, Overlay_Underlay) == 0x000540, "Member 'UPlayerDiscovered_C::Overlay_Underlay' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, Overlay_Container) == 0x000548, "Member 'UPlayerDiscovered_C::Overlay_Container' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, MainLocationText_1) == 0x000550, "Member 'UPlayerDiscovered_C::MainLocationText_1' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, MainLocationText) == 0x000558, "Member 'UPlayerDiscovered_C::MainLocationText' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, MainBox_Landmark) == 0x000560, "Member 'UPlayerDiscovered_C::MainBox_Landmark' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, MainBox) == 0x000568, "Member 'UPlayerDiscovered_C::MainBox' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, Image_BulletRight) == 0x000570, "Member 'UPlayerDiscovered_C::Image_BulletRight' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, Image_BulletLeft) == 0x000578, "Member 'UPlayerDiscovered_C::Image_BulletLeft' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, CommonTextBlock_LandmarkName) == 0x000580, "Member 'UPlayerDiscovered_C::CommonTextBlock_LandmarkName' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, BriefShow) == 0x000588, "Member 'UPlayerDiscovered_C::BriefShow' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, RelevantPlaylistTags) == 0x000590, "Member 'UPlayerDiscovered_C::RelevantPlaylistTags' has a wrong offset!");
static_assert(offsetof(UPlayerDiscovered_C, SoundCue) == 0x0005B0, "Member 'UPlayerDiscovered_C::SoundCue' has a wrong offset!");

}

