#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Player_InAir_AnimBP

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct Player_InAir_AnimBP.Player_InAir_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x1707 (0x1708 - 0x0001)
struct Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_635;                                // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_636;                                // 0x0008(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_637;                                // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_638;                                // 0x0010(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_639;                                // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_640;                                // 0x0018(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_641;                                // 0x001C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_642;                                // 0x0020(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_643;                                // 0x0024(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_644;                                // 0x0028(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_645;                                // 0x002C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_646;                                // 0x0030(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_647;                                // 0x0034(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_648;                                // 0x0038(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_649;                                // 0x003C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_650;                                // 0x0040(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_651;                                // 0x0044(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_652;                                // 0x0048(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_653;                                // 0x004C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_654;                                // 0x0050(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_655;                                // 0x0054(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_656;                                // 0x0058(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_657;                                // 0x005C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<float>                                 __ArrayProperty_658;                               // 0x0060(0x0010)(BlueprintVisible, EditFixedSize)
	TArray<float>                                 __ArrayProperty_659;                               // 0x0070(0x0010)(BlueprintVisible, EditFixedSize)
	class FName                                   __NameProperty_660;                                // 0x0080(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_661;                                 // 0x0084(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_662;                                // 0x0088(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_663;                                 // 0x008C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_664;                                // 0x0090(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_665;                                 // 0x0094(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_666;                                // 0x0098(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_667;                                 // 0x009C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_668;                                // 0x00A0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_669;                                // 0x00A4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_670;                                // 0x00A8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_671;                                // 0x00AC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_672;                                // 0x00B0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_673;                                 // 0x00B4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_674;                                // 0x00B8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_675;                                // 0x00BC(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_676;                                // 0x00C0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_677;                                // 0x00C4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_678;                                // 0x00C8(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_679;                                 // 0x00CC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_680;                               // 0x00D0(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_681;                                // 0x00D4(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnimNodeFunctionRef                   __StructProperty_682;                              // 0x00D8(0x0018)(BlueprintVisible, NoDestructor)
	EBlendListChildUpdateMode                     __EnumProperty_683;                                // 0x00F0(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_684;                                // 0x00F1(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F2[0x6];                                       // 0x00F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_685;                               // 0x00F8(0x0010)(BlueprintVisible, EditFixedSize)
	struct FInputScaleBiasClampConstants          __StructProperty_686;                              // 0x0108(0x002C)(BlueprintVisible, NoDestructor)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            __CurveFloat_687;                                  // 0x0138(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EBlendListChildUpdateMode                     __EnumProperty_688;                                // 0x0140(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAlphaBlendOption                             __EnumProperty_689;                                // 0x0141(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBlendListTransitionType                      __EnumProperty_690;                                // 0x0142(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_143[0x5];                                      // 0x0143(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<float>                                 __ArrayProperty_691;                               // 0x0148(0x0010)(BlueprintVisible, EditFixedSize)
	class UBlendProfile*                          __BlendProfile_692;                                // 0x0158(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          __BoolProperty_693;                                // 0x0160(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x3];                                      // 0x0161(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_694;                               // 0x0164(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_695;                               // 0x0168(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimSyncMethod                               __EnumProperty_696;                                // 0x016C(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_697;                                // 0x016D(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAnimGroupRole                                __ByteProperty_698;                                // 0x016E(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16F[0x1];                                      // 0x016F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   __NameProperty_699;                                // 0x0170(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   __NameProperty_700;                                // 0x0174(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __IntProperty_701;                                 // 0x0178(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNodeFunctionRef                   __StructProperty_702;                              // 0x0180(0x0018)(BlueprintVisible, NoDestructor)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0198(0x0080)()
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0218(0x0040)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_16;                  // 0x0258(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_21;                             // 0x0260(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_15;                  // 0x0290(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_20;                             // 0x0298(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_14;                  // 0x02C8(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_19;                             // 0x02D0(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_13;                  // 0x0300(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_18;                             // 0x0308(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_12;                  // 0x0338(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_17;                             // 0x0368(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_11;                  // 0x0398(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_16;                             // 0x03C8(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_10;                  // 0x03F8(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_15;                             // 0x0400(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_9;                   // 0x0430(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_14;                             // 0x0438(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_8;                   // 0x0468(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_13;                             // 0x0470(0x0030)()
	struct FAnimNodeExposedValueHandler           AnimGraphNode_LinkedInputPose_7;                   // 0x04A0(0x0008)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_12;                             // 0x04A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_11;                             // 0x04D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_10;                             // 0x0508(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_9;                              // 0x0538(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_6;                   // 0x0568(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_8;                              // 0x0598(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_7;                              // 0x05C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_6;                              // 0x05F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_5;                              // 0x0628(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_5;                   // 0x0658(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_4;                              // 0x0688(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_4;                   // 0x06B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_3;                   // 0x06E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_3;                              // 0x0718(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_2;                   // 0x0748(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_2;                              // 0x0778(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose_1;                   // 0x07A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root_1;                              // 0x07D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedInputPose;                     // 0x0808(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SaveCachedPose;                      // 0x0838(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                                // 0x0868(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_6;                   // 0x0898(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_2;                     // 0x08C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                                // 0x08F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_5;                   // 0x0928(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose_1;                     // 0x0958(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_4;                   // 0x0988(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_UseCachedPose;                       // 0x09B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_31;                 // 0x09E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_30;                 // 0x0A18(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_29;                 // 0x0A48(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_28;                 // 0x0A78(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_27;                 // 0x0AA8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_26;                 // 0x0AD8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_25;                 // 0x0B08(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_24;                 // 0x0B38(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_23;                 // 0x0B68(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_22;                 // 0x0B98(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_21;                 // 0x0BC8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_20;                 // 0x0BF8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_19;                 // 0x0C28(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;                 // 0x0C58(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;                 // 0x0C88(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;                 // 0x0CB8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;                 // 0x0CE8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;                 // 0x0D18(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;                 // 0x0D48(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;                 // 0x0D78(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;                 // 0x0DA8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;                 // 0x0DD8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;                  // 0x0E08(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;                  // 0x0E38(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;                  // 0x0E68(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;                  // 0x0E98(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;                   // 0x0EC8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_12;                      // 0x0EF8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;                   // 0x0F28(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_11;                      // 0x0F58(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;                   // 0x0F88(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_10;                      // 0x0FB8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;                    // 0x0FE8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;                       // 0x1018(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;                    // 0x1048(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;                       // 0x1078(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;                    // 0x10A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;                       // 0x10D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;                    // 0x1108(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;                       // 0x1138(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;                  // 0x1168(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_2;                      // 0x1198(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;                       // 0x11C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedAnimLayer_1;                   // 0x11F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;                  // 0x1228(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;                  // 0x1258(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;                  // 0x1288(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;                  // 0x12B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;                    // 0x12E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;                       // 0x1318(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;                    // 0x1348(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;                       // 0x1378(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;                    // 0x13A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;                       // 0x13D8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;                    // 0x1408(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine_1;                      // 0x1438(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;                       // 0x1468(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_LinkedAnimLayer;                     // 0x1498(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;                    // 0x14C8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_3;                   // 0x14F8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;                    // 0x1528(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_2;                   // 0x1558(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer_1;                  // 0x1588(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool_1;                   // 0x15B8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;                      // 0x15E8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;                     // 0x1618(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendSpacePlayer;                    // 0x1648(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;                         // 0x1678(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;                        // 0x16A8(0x0030)()
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_DeadBlending;                        // 0x16D8(0x0030)()
};
static_assert(alignof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData) == 0x001708, "Wrong size on Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_635) == 0x000004, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_635' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_636) == 0x000008, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_636' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_637) == 0x00000C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_637' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_638) == 0x000010, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_638' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_639) == 0x000014, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_639' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_640) == 0x000018, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_640' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_641) == 0x00001C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_641' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_642) == 0x000020, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_642' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_643) == 0x000024, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_643' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_644) == 0x000028, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_644' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_645) == 0x00002C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_645' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_646) == 0x000030, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_646' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_647) == 0x000034, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_647' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_648) == 0x000038, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_648' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_649) == 0x00003C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_649' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_650) == 0x000040, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_650' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_651) == 0x000044, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_651' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_652) == 0x000048, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_652' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_653) == 0x00004C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_653' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_654) == 0x000050, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_654' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_655) == 0x000054, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_655' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_656) == 0x000058, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_656' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_657) == 0x00005C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_657' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_658) == 0x000060, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_658' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_659) == 0x000070, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_659' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_660) == 0x000080, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_660' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_661) == 0x000084, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_661' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_662) == 0x000088, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_662' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_663) == 0x00008C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_663' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_664) == 0x000090, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_664' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_665) == 0x000094, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_665' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_666) == 0x000098, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_666' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_667) == 0x00009C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_667' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_668) == 0x0000A0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_668' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_669) == 0x0000A4, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_669' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_670) == 0x0000A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_670' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_671) == 0x0000AC, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_671' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_672) == 0x0000B0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_672' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_673) == 0x0000B4, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_673' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_674) == 0x0000B8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_674' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_675) == 0x0000BC, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_675' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_676) == 0x0000C0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_676' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_677) == 0x0000C4, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_677' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_678) == 0x0000C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_678' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_679) == 0x0000CC, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_679' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_680) == 0x0000D0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_680' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_681) == 0x0000D4, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_681' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_682) == 0x0000D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_682' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_683) == 0x0000F0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_683' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_684) == 0x0000F1, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_684' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_685) == 0x0000F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_685' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_686) == 0x000108, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_686' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __CurveFloat_687) == 0x000138, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__CurveFloat_687' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_688) == 0x000140, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_688' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_689) == 0x000141, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_689' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_690) == 0x000142, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_690' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __ArrayProperty_691) == 0x000148, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__ArrayProperty_691' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __BlendProfile_692) == 0x000158, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__BlendProfile_692' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_693) == 0x000160, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_693' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_694) == 0x000164, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_694' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __FloatProperty_695) == 0x000168, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__FloatProperty_695' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __EnumProperty_696) == 0x00016C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__EnumProperty_696' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __BoolProperty_697) == 0x00016D, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__BoolProperty_697' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __ByteProperty_698) == 0x00016E, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__ByteProperty_698' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_699) == 0x000170, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_699' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __NameProperty_700) == 0x000174, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__NameProperty_700' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __IntProperty_701) == 0x000178, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__IntProperty_701' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, __StructProperty_702) == 0x000180, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::__StructProperty_702' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_PropertyAccess) == 0x000198, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimBlueprintExtension_Base) == 0x000218, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_16) == 0x000258, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_16' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_21) == 0x000260, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_21' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_15) == 0x000290, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_15' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_20) == 0x000298, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_20' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_14) == 0x0002C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_14' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_19) == 0x0002D0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_19' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_13) == 0x000300, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_13' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_18) == 0x000308, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_18' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_12) == 0x000338, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_12' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_17) == 0x000368, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_17' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_11) == 0x000398, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_11' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_16) == 0x0003C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_16' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_10) == 0x0003F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_10' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_15) == 0x000400, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_15' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_9) == 0x000430, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_9' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_14) == 0x000438, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_14' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_8) == 0x000468, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_8' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_13) == 0x000470, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_13' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_7) == 0x0004A0, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_12) == 0x0004A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_12' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_11) == 0x0004D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_11' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_10) == 0x000508, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_10' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_9) == 0x000538, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_6) == 0x000568, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_8) == 0x000598, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_7) == 0x0005C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_6) == 0x0005F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_5) == 0x000628, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_5) == 0x000658, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_4) == 0x000688, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_4) == 0x0006B8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_3) == 0x0006E8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_3) == 0x000718, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_2) == 0x000748, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_2) == 0x000778, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose_1) == 0x0007A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root_1) == 0x0007D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedInputPose) == 0x000808, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SaveCachedPose) == 0x000838, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Root) == 0x000868, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_6) == 0x000898, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose_2) == 0x0008C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_Slot) == 0x0008F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_5) == 0x000928, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose_1) == 0x000958, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_4) == 0x000988, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_UseCachedPose) == 0x0009B8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_31) == 0x0009E8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_31' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_30) == 0x000A18, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_30' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_29) == 0x000A48, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_29' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_28) == 0x000A78, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_28' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_27) == 0x000AA8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_27' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_26) == 0x000AD8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_26' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_25) == 0x000B08, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_25' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_24) == 0x000B38, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_24' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_23) == 0x000B68, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_23' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_22) == 0x000B98, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_22' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_21) == 0x000BC8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_21' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_20) == 0x000BF8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_20' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_19) == 0x000C28, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_19' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_18) == 0x000C58, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_18' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_17) == 0x000C88, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_17' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_16) == 0x000CB8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_16' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_15) == 0x000CE8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_15' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_14) == 0x000D18, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_14' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_13) == 0x000D48, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_13' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_12) == 0x000D78, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_12' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_11) == 0x000DA8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_10) == 0x000DD8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_9) == 0x000E08, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_8) == 0x000E38, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_7) == 0x000E68, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_6) == 0x000E98, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_12) == 0x000EC8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_12) == 0x000EF8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_12' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_11) == 0x000F28, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_11) == 0x000F58, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_11' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_10) == 0x000F88, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_10) == 0x000FB8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_10' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_9) == 0x000FE8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_9) == 0x001018, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_9' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_8) == 0x001048, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_8) == 0x001078, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_8' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_7) == 0x0010A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_7) == 0x0010D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_6) == 0x001108, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_6) == 0x001138, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_5) == 0x001168, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine_2) == 0x001198, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_5) == 0x0011C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedAnimLayer_1) == 0x0011F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedAnimLayer_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_4) == 0x001228, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_3) == 0x001258, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_2) == 0x001288, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult_1) == 0x0012B8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_5) == 0x0012E8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_4) == 0x001318, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_4) == 0x001348, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_3) == 0x001378, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_3) == 0x0013A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_2) == 0x0013D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_TransitionResult) == 0x001408, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine_1) == 0x001438, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult_1) == 0x001468, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_LinkedAnimLayer) == 0x001498, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_2) == 0x0014C8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_3) == 0x0014F8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer_1) == 0x001528, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_2) == 0x001558, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendSpacePlayer_1) == 0x001588, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool_1) == 0x0015B8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_SequencePlayer) == 0x0015E8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendListByBool) == 0x001618, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_BlendSpacePlayer) == 0x001648, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateResult) == 0x001678, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_StateMachine) == 0x0016A8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData, AnimGraphNode_DeadBlending) == 0x0016D8, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedConstantData::AnimGraphNode_DeadBlending' has a wrong offset!");

// ScriptStruct Player_InAir_AnimBP.Player_InAir_AnimBP_C.AnimBlueprintGeneratedMutableData
// 0x0017 (0x0018 - 0x0001)
struct Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	bool                                          __BoolProperty;                                    // 0x0001(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_0;                                  // 0x0002(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_1;                                  // 0x0003(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         __FloatProperty_2;                                 // 0x0004(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_3;                                  // 0x0008(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_4;                                  // 0x0009(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_5;                                 // 0x000C(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_6;                                  // 0x0010(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          __BoolProperty_7;                                  // 0x0011(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         __FloatProperty_8;                                 // 0x0014(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData) == 0x000004, "Wrong alignment on Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(sizeof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData) == 0x000018, "Wrong size on Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty) == 0x000001, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_0) == 0x000002, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_0' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_1) == 0x000003, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_1' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_2) == 0x000004, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_2' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_3) == 0x000008, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_3' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_4) == 0x000009, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_4' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_5) == 0x00000C, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_5' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_6) == 0x000010, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_6' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __BoolProperty_7) == 0x000011, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__BoolProperty_7' has a wrong offset!");
static_assert(offsetof(Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData, __FloatProperty_8) == 0x000014, "Member 'Player_InAir_AnimBP::FAnimBlueprintGeneratedMutableData::__FloatProperty_8' has a wrong offset!");

}

