#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerAIPetRuntime

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlayerAIPetRuntime.PlayerAIPetCheatManager.CustomPlayerPetCheat
// 0x0040 (0x0040 - 0x0000)
struct PlayerAIPetCheatManager_CustomPlayerPetCheat final
{
public:
	class FString                                 Command;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param1;                                            // 0x0010(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param2;                                            // 0x0020(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param3;                                            // 0x0030(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerAIPetCheatManager_CustomPlayerPetCheat) == 0x000008, "Wrong alignment on PlayerAIPetCheatManager_CustomPlayerPetCheat");
static_assert(sizeof(PlayerAIPetCheatManager_CustomPlayerPetCheat) == 0x000040, "Wrong size on PlayerAIPetCheatManager_CustomPlayerPetCheat");
static_assert(offsetof(PlayerAIPetCheatManager_CustomPlayerPetCheat, Command) == 0x000000, "Member 'PlayerAIPetCheatManager_CustomPlayerPetCheat::Command' has a wrong offset!");
static_assert(offsetof(PlayerAIPetCheatManager_CustomPlayerPetCheat, Param1) == 0x000010, "Member 'PlayerAIPetCheatManager_CustomPlayerPetCheat::Param1' has a wrong offset!");
static_assert(offsetof(PlayerAIPetCheatManager_CustomPlayerPetCheat, Param2) == 0x000020, "Member 'PlayerAIPetCheatManager_CustomPlayerPetCheat::Param2' has a wrong offset!");
static_assert(offsetof(PlayerAIPetCheatManager_CustomPlayerPetCheat, Param3) == 0x000030, "Member 'PlayerAIPetCheatManager_CustomPlayerPetCheat::Param3' has a wrong offset!");

// Function PlayerAIPetRuntime.PlayerAIPetCheatManager.SpawnPlayerPet
// 0x0010 (0x0010 - 0x0000)
struct PlayerAIPetCheatManager_SpawnPlayerPet final
{
public:
	class FString                                 PetToSpawn;                                        // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerAIPetCheatManager_SpawnPlayerPet) == 0x000008, "Wrong alignment on PlayerAIPetCheatManager_SpawnPlayerPet");
static_assert(sizeof(PlayerAIPetCheatManager_SpawnPlayerPet) == 0x000010, "Wrong size on PlayerAIPetCheatManager_SpawnPlayerPet");
static_assert(offsetof(PlayerAIPetCheatManager_SpawnPlayerPet, PetToSpawn) == 0x000000, "Member 'PlayerAIPetCheatManager_SpawnPlayerPet::PetToSpawn' has a wrong offset!");

// Function PlayerAIPetRuntime.PlayerAIPetCheatManager.SpawnPlayerPetForAllPlayers
// 0x0010 (0x0010 - 0x0000)
struct PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers final
{
public:
	class FString                                 PetToSpawn;                                        // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers) == 0x000008, "Wrong alignment on PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers");
static_assert(sizeof(PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers) == 0x000010, "Wrong size on PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers");
static_assert(offsetof(PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers, PetToSpawn) == 0x000000, "Member 'PlayerAIPetCheatManager_SpawnPlayerPetForAllPlayers::PetToSpawn' has a wrong offset!");

// Function PlayerAIPetRuntime.FortAIPawnComponent_PlayerAIPet.OnPetSpawned
// 0x0008 (0x0008 - 0x0000)
struct FortAIPawnComponent_PlayerAIPet_OnPetSpawned final
{
public:
	class AFortPlayerPawn*                        Player;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortAIPawnComponent_PlayerAIPet_OnPetSpawned) == 0x000008, "Wrong alignment on FortAIPawnComponent_PlayerAIPet_OnPetSpawned");
static_assert(sizeof(FortAIPawnComponent_PlayerAIPet_OnPetSpawned) == 0x000008, "Wrong size on FortAIPawnComponent_PlayerAIPet_OnPetSpawned");
static_assert(offsetof(FortAIPawnComponent_PlayerAIPet_OnPetSpawned, Player) == 0x000000, "Member 'FortAIPawnComponent_PlayerAIPet_OnPetSpawned::Player' has a wrong offset!");

// Function PlayerAIPetRuntime.FortAIPawnComponent_PlayerAIPet.SetCurrentPlayer
// 0x0008 (0x0008 - 0x0000)
struct FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer final
{
public:
	class AFortPlayerPawn*                        NewPlayer;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer) == 0x000008, "Wrong alignment on FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer");
static_assert(sizeof(FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer) == 0x000008, "Wrong size on FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer");
static_assert(offsetof(FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer, NewPlayer) == 0x000000, "Member 'FortAIPawnComponent_PlayerAIPet_SetCurrentPlayer::NewPlayer' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.AttachPet
// 0x0001 (0x0001 - 0x0000)
struct FortControllerComponent_PlayerAIPet_AttachPet final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_AttachPet) == 0x000001, "Wrong alignment on FortControllerComponent_PlayerAIPet_AttachPet");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_AttachPet) == 0x000001, "Wrong size on FortControllerComponent_PlayerAIPet_AttachPet");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_AttachPet, ReturnValue) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_AttachPet::ReturnValue' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.CustomCheat
// 0x0040 (0x0040 - 0x0000)
struct FortControllerComponent_PlayerAIPet_CustomCheat final
{
public:
	class FString                                 Command;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param1;                                            // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param2;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Param3;                                            // 0x0030(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_CustomCheat) == 0x000008, "Wrong alignment on FortControllerComponent_PlayerAIPet_CustomCheat");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_CustomCheat) == 0x000040, "Wrong size on FortControllerComponent_PlayerAIPet_CustomCheat");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_CustomCheat, Command) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_CustomCheat::Command' has a wrong offset!");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_CustomCheat, Param1) == 0x000010, "Member 'FortControllerComponent_PlayerAIPet_CustomCheat::Param1' has a wrong offset!");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_CustomCheat, Param2) == 0x000020, "Member 'FortControllerComponent_PlayerAIPet_CustomCheat::Param2' has a wrong offset!");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_CustomCheat, Param3) == 0x000030, "Member 'FortControllerComponent_PlayerAIPet_CustomCheat::Param3' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.DespawnPet
// 0x0001 (0x0001 - 0x0000)
struct FortControllerComponent_PlayerAIPet_DespawnPet final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_DespawnPet) == 0x000001, "Wrong alignment on FortControllerComponent_PlayerAIPet_DespawnPet");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_DespawnPet) == 0x000001, "Wrong size on FortControllerComponent_PlayerAIPet_DespawnPet");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_DespawnPet, ReturnValue) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_DespawnPet::ReturnValue' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.DetachPet
// 0x0001 (0x0001 - 0x0000)
struct FortControllerComponent_PlayerAIPet_DetachPet final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_DetachPet) == 0x000001, "Wrong alignment on FortControllerComponent_PlayerAIPet_DetachPet");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_DetachPet) == 0x000001, "Wrong size on FortControllerComponent_PlayerAIPet_DetachPet");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_DetachPet, ReturnValue) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_DetachPet::ReturnValue' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.SetCurrentPet
// 0x0008 (0x0008 - 0x0000)
struct FortControllerComponent_PlayerAIPet_SetCurrentPet final
{
public:
	class AFortAIPawn*                            NewPet;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_SetCurrentPet) == 0x000008, "Wrong alignment on FortControllerComponent_PlayerAIPet_SetCurrentPet");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_SetCurrentPet) == 0x000008, "Wrong size on FortControllerComponent_PlayerAIPet_SetCurrentPet");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_SetCurrentPet, NewPet) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_SetCurrentPet::NewPet' has a wrong offset!");

// Function PlayerAIPetRuntime.FortControllerComponent_PlayerAIPet.SpawnPet
// 0x0010 (0x0010 - 0x0000)
struct FortControllerComponent_PlayerAIPet_SpawnPet final
{
public:
	class FString                                 PetToSpawn;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortControllerComponent_PlayerAIPet_SpawnPet) == 0x000008, "Wrong alignment on FortControllerComponent_PlayerAIPet_SpawnPet");
static_assert(sizeof(FortControllerComponent_PlayerAIPet_SpawnPet) == 0x000010, "Wrong size on FortControllerComponent_PlayerAIPet_SpawnPet");
static_assert(offsetof(FortControllerComponent_PlayerAIPet_SpawnPet, PetToSpawn) == 0x000000, "Member 'FortControllerComponent_PlayerAIPet_SpawnPet::PetToSpawn' has a wrong offset!");

}

