#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProgressiveHeaderBanner

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.ExecuteUbergraph_ProgressiveHeaderBanner
// 0x0008 (0x0008 - 0x0000)
struct ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner) == 0x000004, "Wrong alignment on ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner");
static_assert(sizeof(ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner) == 0x000008, "Wrong size on ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner");
static_assert(offsetof(ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner, EntryPoint) == 0x000000, "Member 'ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner::EntryPoint' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner, K2Node_Event_IsDesignTime) == 0x000004, "Member 'ProgressiveHeaderBanner_C_ExecuteUbergraph_ProgressiveHeaderBanner::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct ProgressiveHeaderBanner_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C_PreConstruct) == 0x000001, "Wrong alignment on ProgressiveHeaderBanner_C_PreConstruct");
static_assert(sizeof(ProgressiveHeaderBanner_C_PreConstruct) == 0x000001, "Wrong size on ProgressiveHeaderBanner_C_PreConstruct");
static_assert(offsetof(ProgressiveHeaderBanner_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'ProgressiveHeaderBanner_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.Update Banner State
// 0x0050 (0x0050 - 0x0000)
struct ProgressiveHeaderBanner_C_Update_Banner_State final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          Current_Sets_Complete;                             // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Subscribed_0;                                      // 0x0011(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Unlocked_Color;                                    // 0x0014(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Locked_Color;                                      // 0x0024(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_Get_Image_ReturnValue;                    // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C_Update_Banner_State) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C_Update_Banner_State");
static_assert(sizeof(ProgressiveHeaderBanner_C_Update_Banner_State) == 0x000050, "Wrong size on ProgressiveHeaderBanner_C_Update_Banner_State");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, Text) == 0x000000, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::Text' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, Current_Sets_Complete) == 0x000010, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::Current_Sets_Complete' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, Subscribed_0) == 0x000011, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::Subscribed_0' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, Unlocked_Color) == 0x000014, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::Unlocked_Color' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, Locked_Color) == 0x000024, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::Locked_Color' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, CallFunc_Get_Image_ReturnValue) == 0x000038, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::CallFunc_Get_Image_ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Banner_State, CallFunc_SelectColor_ReturnValue) == 0x000040, "Member 'ProgressiveHeaderBanner_C_Update_Banner_State::CallFunc_SelectColor_ReturnValue' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.Update Text
// 0x0018 (0x0018 - 0x0000)
struct ProgressiveHeaderBanner_C_Update_Text final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C_Update_Text) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C_Update_Text");
static_assert(sizeof(ProgressiveHeaderBanner_C_Update_Text) == 0x000018, "Wrong size on ProgressiveHeaderBanner_C_Update_Text");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, InText) == 0x000000, "Member 'ProgressiveHeaderBanner_C_Update_Text::InText' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, Temp_bool_Variable) == 0x000010, "Member 'ProgressiveHeaderBanner_C_Update_Text::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, CallFunc_TextIsEmpty_ReturnValue) == 0x000011, "Member 'ProgressiveHeaderBanner_C_Update_Text::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, Temp_byte_Variable) == 0x000012, "Member 'ProgressiveHeaderBanner_C_Update_Text::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, Temp_byte_Variable_1) == 0x000013, "Member 'ProgressiveHeaderBanner_C_Update_Text::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Update_Text, K2Node_Select_Default) == 0x000014, "Member 'ProgressiveHeaderBanner_C_Update_Text::K2Node_Select_Default' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.__5243a4a0-43af-6341-c391-7a81986bb43f_SourceToDest
// 0x0018 (0x0018 - 0x0000)
struct ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest final
{
public:
	class UTexture2D*                             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSubscribed_ReturnValue;                 // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             CallFunc_Get_Image_ReturnValue;                    // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest");
static_assert(sizeof(ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest) == 0x000018, "Wrong size on ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest");
static_assert(offsetof(ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest, ReturnValue) == 0x000000, "Member 'ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest::ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest, CallFunc_IsSubscribed_ReturnValue) == 0x000008, "Member 'ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest::CallFunc_IsSubscribed_ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest, CallFunc_Get_Image_ReturnValue) == 0x000010, "Member 'ProgressiveHeaderBanner_C___5243a4a0_43af_6341_c391_7a81986bb43f_SourceToDest::CallFunc_Get_Image_ReturnValue' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.__5a3c60cd-432a-0530-fee4-5b909725cc3c_SourceToDest
// 0x0020 (0x0020 - 0x0000)
struct ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
	class FText                                   CallFunc_SelectText_ReturnValue;                   // 0x0010(0x0010)()
};
static_assert(alignof(ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest");
static_assert(sizeof(ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest) == 0x000020, "Wrong size on ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest");
static_assert(offsetof(ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest, ReturnValue) == 0x000000, "Member 'ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest::ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest, CallFunc_SelectText_ReturnValue) == 0x000010, "Member 'ProgressiveHeaderBanner_C___5a3c60cd_432a_0530_fee4_5b909725cc3c_SourceToDest::CallFunc_SelectText_ReturnValue' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.__6f087cdb-4232-6c12-ffb7-6faf52596423_SourceToDest
// 0x0024 (0x0024 - 0x0000)
struct ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSubscribed_ReturnValue;                 // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0014(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest) == 0x000004, "Wrong alignment on ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest");
static_assert(sizeof(ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest) == 0x000024, "Wrong size on ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest");
static_assert(offsetof(ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest, ReturnValue) == 0x000000, "Member 'ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest::ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest, CallFunc_IsSubscribed_ReturnValue) == 0x000010, "Member 'ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest::CallFunc_IsSubscribed_ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest, CallFunc_SelectColor_ReturnValue) == 0x000014, "Member 'ProgressiveHeaderBanner_C___6f087cdb_4232_6c12_ffb7_6faf52596423_SourceToDest::CallFunc_SelectColor_ReturnValue' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.Get Banner Text
// 0x0028 (0x0028 - 0x0000)
struct ProgressiveHeaderBanner_C_Get_Banner_Text final
{
public:
	bool                                          All_Complete;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Result;                                            // 0x0008(0x0010)(Parm, OutParm)
	class FText                                   CallFunc_SelectText_ReturnValue;                   // 0x0018(0x0010)()
};
static_assert(alignof(ProgressiveHeaderBanner_C_Get_Banner_Text) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C_Get_Banner_Text");
static_assert(sizeof(ProgressiveHeaderBanner_C_Get_Banner_Text) == 0x000028, "Wrong size on ProgressiveHeaderBanner_C_Get_Banner_Text");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Banner_Text, All_Complete) == 0x000000, "Member 'ProgressiveHeaderBanner_C_Get_Banner_Text::All_Complete' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Banner_Text, Result) == 0x000008, "Member 'ProgressiveHeaderBanner_C_Get_Banner_Text::Result' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Banner_Text, CallFunc_SelectText_ReturnValue) == 0x000018, "Member 'ProgressiveHeaderBanner_C_Get_Banner_Text::CallFunc_SelectText_ReturnValue' has a wrong offset!");

// Function ProgressiveHeaderBanner.ProgressiveHeaderBanner_C.Get Image
// 0x0030 (0x0030 - 0x0000)
struct ProgressiveHeaderBanner_C_Get_Image final
{
public:
	bool                                          Subscribed_0;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          All_Sets_Complete;                                 // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable;                              // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_1;                            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_Select_Default;                             // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ProgressiveHeaderBanner_C_Get_Image) == 0x000008, "Wrong alignment on ProgressiveHeaderBanner_C_Get_Image");
static_assert(sizeof(ProgressiveHeaderBanner_C_Get_Image) == 0x000030, "Wrong size on ProgressiveHeaderBanner_C_Get_Image");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, Subscribed_0) == 0x000000, "Member 'ProgressiveHeaderBanner_C_Get_Image::Subscribed_0' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, All_Sets_Complete) == 0x000001, "Member 'ProgressiveHeaderBanner_C_Get_Image::All_Sets_Complete' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, ReturnValue) == 0x000008, "Member 'ProgressiveHeaderBanner_C_Get_Image::ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, Temp_bool_Variable) == 0x000010, "Member 'ProgressiveHeaderBanner_C_Get_Image::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, CallFunc_BooleanOR_ReturnValue) == 0x000011, "Member 'ProgressiveHeaderBanner_C_Get_Image::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, Temp_object_Variable) == 0x000018, "Member 'ProgressiveHeaderBanner_C_Get_Image::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, Temp_object_Variable_1) == 0x000020, "Member 'ProgressiveHeaderBanner_C_Get_Image::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(ProgressiveHeaderBanner_C_Get_Image, K2Node_Select_Default) == 0x000028, "Member 'ProgressiveHeaderBanner_C_Get_Image::K2Node_Select_Default' has a wrong offset!");

}

