#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SidebarUserListEntry_MutualFriend

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SidebarUserListEntry_MutualFriend.SidebarUserListEntry_MutualFriend_C
// 0x0040 (0x1610 - 0x15D0)
class USidebarUserListEntry_MutualFriend_C final : public UFortMutualFriendSocialUserListEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x15D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   Text_DisplayName;                                  // 0x15D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      EmptyButtonToEatOneMouseUpEvent;                   // 0x15E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           EncourageEpicFriend_IdleColor;                     // 0x15E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           EncourageEpicFriend_HoveredColor;                  // 0x15F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SidebarUserListEntry_MutualFriend(int32 EntryPoint);
	void OnNewAvatarsEnabledChanged(bool bUsingNewAvatars);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SidebarUserListEntry_MutualFriend_C">();
	}
	static class USidebarUserListEntry_MutualFriend_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USidebarUserListEntry_MutualFriend_C>();
	}
};
static_assert(alignof(USidebarUserListEntry_MutualFriend_C) == 0x000010, "Wrong alignment on USidebarUserListEntry_MutualFriend_C");
static_assert(sizeof(USidebarUserListEntry_MutualFriend_C) == 0x001610, "Wrong size on USidebarUserListEntry_MutualFriend_C");
static_assert(offsetof(USidebarUserListEntry_MutualFriend_C, UberGraphFrame) == 0x0015D0, "Member 'USidebarUserListEntry_MutualFriend_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USidebarUserListEntry_MutualFriend_C, Text_DisplayName) == 0x0015D8, "Member 'USidebarUserListEntry_MutualFriend_C::Text_DisplayName' has a wrong offset!");
static_assert(offsetof(USidebarUserListEntry_MutualFriend_C, EmptyButtonToEatOneMouseUpEvent) == 0x0015E0, "Member 'USidebarUserListEntry_MutualFriend_C::EmptyButtonToEatOneMouseUpEvent' has a wrong offset!");
static_assert(offsetof(USidebarUserListEntry_MutualFriend_C, EncourageEpicFriend_IdleColor) == 0x0015E8, "Member 'USidebarUserListEntry_MutualFriend_C::EncourageEpicFriend_IdleColor' has a wrong offset!");
static_assert(offsetof(USidebarUserListEntry_MutualFriend_C, EncourageEpicFriend_HoveredColor) == 0x0015F8, "Member 'USidebarUserListEntry_MutualFriend_C::EncourageEpicFriend_HoveredColor' has a wrong offset!");

}

