#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SuggestedFriendListEntry

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SuggestedFriendListEntry.SuggestedFriendListEntry_C
// 0x0060 (0x1640 - 0x15E0)
class USuggestedFriendListEntry_C final : public UFortConnectionsUserListEntry
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x15E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUserActionMenuInputButton_C*           UserActionMenuInputButton;                         // 0x15E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      EmptyButtonToEatOneMouseUpEvent;                   // 0x15F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Highlight;                                  // 0x15F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Background;                                 // 0x1600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Arrow;                                             // 0x1608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hovered;                                           // 0x1610(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Selected;                                          // 0x1618(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           EncourageEpicFriend_IdleColor;                     // 0x1620(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           EncourageEpicFriend_HoveredColor;                  // 0x1630(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__MenuAnchor_Actions_K2Node_ComponentBoundEvent_0_OnMenuOpenChangedEvent__DelegateSignature(bool bIsOpen);
	void BP_OnHovered();
	void BP_OnUnhovered();
	void ExecuteUbergraph_SuggestedFriendListEntry(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SuggestedFriendListEntry_C">();
	}
	static class USuggestedFriendListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USuggestedFriendListEntry_C>();
	}
};
static_assert(alignof(USuggestedFriendListEntry_C) == 0x000010, "Wrong alignment on USuggestedFriendListEntry_C");
static_assert(sizeof(USuggestedFriendListEntry_C) == 0x001640, "Wrong size on USuggestedFriendListEntry_C");
static_assert(offsetof(USuggestedFriendListEntry_C, UberGraphFrame) == 0x0015E0, "Member 'USuggestedFriendListEntry_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, UserActionMenuInputButton) == 0x0015E8, "Member 'USuggestedFriendListEntry_C::UserActionMenuInputButton' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, EmptyButtonToEatOneMouseUpEvent) == 0x0015F0, "Member 'USuggestedFriendListEntry_C::EmptyButtonToEatOneMouseUpEvent' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, Border_Highlight) == 0x0015F8, "Member 'USuggestedFriendListEntry_C::Border_Highlight' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, Border_Background) == 0x001600, "Member 'USuggestedFriendListEntry_C::Border_Background' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, Arrow) == 0x001608, "Member 'USuggestedFriendListEntry_C::Arrow' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, Hovered) == 0x001610, "Member 'USuggestedFriendListEntry_C::Hovered' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, Selected) == 0x001618, "Member 'USuggestedFriendListEntry_C::Selected' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, EncourageEpicFriend_IdleColor) == 0x001620, "Member 'USuggestedFriendListEntry_C::EncourageEpicFriend_IdleColor' has a wrong offset!");
static_assert(offsetof(USuggestedFriendListEntry_C, EncourageEpicFriend_HoveredColor) == 0x001630, "Member 'USuggestedFriendListEntry_C::EncourageEpicFriend_HoveredColor' has a wrong offset!");

}

