#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TwinStretchCornRuntime

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function TwinStretchCornRuntime.FortPlayerViewFollowerComponent.GetRelativeOffsetFromPlayer
// 0x0018 (0x0018 - 0x0000)
struct FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer final
{
public:
	struct FVector                                ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer) == 0x000008, "Wrong alignment on FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer");
static_assert(sizeof(FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer) == 0x000018, "Wrong size on FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer");
static_assert(offsetof(FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer, ReturnValue) == 0x000000, "Member 'FortPlayerViewFollowerComponent_GetRelativeOffsetFromPlayer::ReturnValue' has a wrong offset!");

// Function TwinStretchCornRuntime.TwinStretchCornShieldInterface.GetShieldIsActive
// 0x0001 (0x0001 - 0x0000)
struct TwinStretchCornShieldInterface_GetShieldIsActive final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(TwinStretchCornShieldInterface_GetShieldIsActive) == 0x000001, "Wrong alignment on TwinStretchCornShieldInterface_GetShieldIsActive");
static_assert(sizeof(TwinStretchCornShieldInterface_GetShieldIsActive) == 0x000001, "Wrong size on TwinStretchCornShieldInterface_GetShieldIsActive");
static_assert(offsetof(TwinStretchCornShieldInterface_GetShieldIsActive, ReturnValue) == 0x000000, "Member 'TwinStretchCornShieldInterface_GetShieldIsActive::ReturnValue' has a wrong offset!");

// Function TwinStretchCornRuntime.TwinStretchCornWeaponInterface.GetShieldActor
// 0x0008 (0x0008 - 0x0000)
struct TwinStretchCornWeaponInterface_GetShieldActor final
{
public:
	class AActor*                                 ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(TwinStretchCornWeaponInterface_GetShieldActor) == 0x000008, "Wrong alignment on TwinStretchCornWeaponInterface_GetShieldActor");
static_assert(sizeof(TwinStretchCornWeaponInterface_GetShieldActor) == 0x000008, "Wrong size on TwinStretchCornWeaponInterface_GetShieldActor");
static_assert(offsetof(TwinStretchCornWeaponInterface_GetShieldActor, ReturnValue) == 0x000000, "Member 'TwinStretchCornWeaponInterface_GetShieldActor::ReturnValue' has a wrong offset!");

}

