#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VividRazorCoreGameplayRuntime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// Class VividRazorCoreGameplayRuntime.VividRazorPlayspace
// 0x0000 (0x06E0 - 0x06E0)
class AVividRazorPlayspace final : public AFortPlayspace
{
public:
	float GetPlayspaceRatingForContext(const class UObject* WorldContextObject);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VividRazorPlayspace">();
	}
	static class AVividRazorPlayspace* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVividRazorPlayspace>();
	}
};
static_assert(alignof(AVividRazorPlayspace) == 0x000008, "Wrong alignment on AVividRazorPlayspace");
static_assert(sizeof(AVividRazorPlayspace) == 0x0006E0, "Wrong size on AVividRazorPlayspace");

}

