#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CreatorPage_Button_Link

#include "Basic.hpp"

#include "WBP_CreatorPage_Button_Link_classes.hpp"
#include "WBP_CreatorPage_Button_Link_parameters.hpp"


namespace SDK
{

// Function WBP_CreatorPage_Button_Link.WBP_CreatorPage_Button_Link_C.BP_OnFocusReceived
// (Event, Protected, BlueprintEvent)

void UWBP_CreatorPage_Button_Link_C::BP_OnFocusReceived()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnFocusReceived");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CreatorPage_Button_Link.WBP_CreatorPage_Button_Link_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CreatorPage_Button_Link_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CreatorPage_Button_Link.WBP_CreatorPage_Button_Link_C.ExecuteUbergraph_WBP_CreatorPage_Button_Link
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CreatorPage_Button_Link_C::ExecuteUbergraph_WBP_CreatorPage_Button_Link(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_WBP_CreatorPage_Button_Link");

	Params::WBP_CreatorPage_Button_Link_C_ExecuteUbergraph_WBP_CreatorPage_Button_Link Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CreatorPage_Button_Link.WBP_CreatorPage_Button_Link_C.SetMobileStyle
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_CreatorPage_Button_Link_C::SetMobileStyle()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMobileStyle");

	UObject::ProcessEvent(Func, nullptr);
}

}

