#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonPassBanner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_UIKit_Tag_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_SeasonPassBanner.WBP_SeasonPassBanner_C
// 0x0008 (0x0728 - 0x0720)
class UWBP_SeasonPassBanner_C final : public UWBP_UIKit_Tag_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_SeasonPassBanner_C;             // 0x0720(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_SeasonPassBanner(int32 EntryPoint);
	void LoadPassData(TSoftObjectPtr<class USeasonPassData> PassDataSoftObject);
	void OnLoaded_2D0125EB427C4DAD0EA1E9BC7828D258(class UObject* Loaded);
	void OnLoaded_3206EBE448E7DD93D8961FA2CBE97CFF(class UObject* Loaded);
	void SetSeasonItem(class UFortSeasonItem* SeasonItem, bool IsAllowed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_SeasonPassBanner_C">();
	}
	static class UWBP_SeasonPassBanner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_SeasonPassBanner_C>();
	}
};
static_assert(alignof(UWBP_SeasonPassBanner_C) == 0x000008, "Wrong alignment on UWBP_SeasonPassBanner_C");
static_assert(sizeof(UWBP_SeasonPassBanner_C) == 0x000728, "Wrong size on UWBP_SeasonPassBanner_C");
static_assert(offsetof(UWBP_SeasonPassBanner_C, UberGraphFrame_WBP_SeasonPassBanner_C) == 0x000720, "Member 'UWBP_SeasonPassBanner_C::UberGraphFrame_WBP_SeasonPassBanner_C' has a wrong offset!");

}

