#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ArrowButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_ArrowButton.WBP_ArrowButton_C.ExecuteUbergraph_WBP_ArrowButton
// 0x0008 (0x0008 - 0x0000)
struct WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton) == 0x000004, "Wrong alignment on WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton");
static_assert(sizeof(WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton) == 0x000008, "Wrong size on WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton");
static_assert(offsetof(WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton, EntryPoint) == 0x000000, "Member 'WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_ArrowButton_C_ExecuteUbergraph_WBP_ArrowButton::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function WBP_ArrowButton.WBP_ArrowButton_C.InverseArrowDirection
// 0x0060 (0x0060 - 0x0000)
struct WBP_ArrowButton_C_InverseArrowDirection final
{
public:
	bool                                          InverseArrow_0;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable;                              // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Temp_struct_Variable_1;                            // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_real_Variable;                                // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_real_Variable_1;                              // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHorizontalAlignment                          K2Node_Select_Default;                             // 0x0035(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_1;                           // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              K2Node_Select_Default_2;                           // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_UIKit_Block_Image_C*               K2Node_DynamicCast_AsWBP_UIKit_Block_Image;        // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ArrowButton_C_InverseArrowDirection) == 0x000008, "Wrong alignment on WBP_ArrowButton_C_InverseArrowDirection");
static_assert(sizeof(WBP_ArrowButton_C_InverseArrowDirection) == 0x000060, "Wrong size on WBP_ArrowButton_C_InverseArrowDirection");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, InverseArrow_0) == 0x000000, "Member 'WBP_ArrowButton_C_InverseArrowDirection::InverseArrow_0' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_byte_Variable) == 0x000001, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_byte_Variable_1) == 0x000002, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_bool_Variable) == 0x000003, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_struct_Variable) == 0x000008, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_struct_Variable_1) == 0x000018, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_bool_Variable_1) == 0x000028, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_real_Variable) == 0x00002C, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_real_Variable_1) == 0x000030, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, Temp_bool_Variable_2) == 0x000034, "Member 'WBP_ArrowButton_C_InverseArrowDirection::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, K2Node_Select_Default) == 0x000035, "Member 'WBP_ArrowButton_C_InverseArrowDirection::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, K2Node_Select_Default_1) == 0x000038, "Member 'WBP_ArrowButton_C_InverseArrowDirection::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, K2Node_Select_Default_2) == 0x000040, "Member 'WBP_ArrowButton_C_InverseArrowDirection::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, K2Node_DynamicCast_AsWBP_UIKit_Block_Image) == 0x000050, "Member 'WBP_ArrowButton_C_InverseArrowDirection::K2Node_DynamicCast_AsWBP_UIKit_Block_Image' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_InverseArrowDirection, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'WBP_ArrowButton_C_InverseArrowDirection::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_ArrowButton.WBP_ArrowButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_ArrowButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ArrowButton_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_ArrowButton_C_PreConstruct");
static_assert(sizeof(WBP_ArrowButton_C_PreConstruct) == 0x000001, "Wrong size on WBP_ArrowButton_C_PreConstruct");
static_assert(offsetof(WBP_ArrowButton_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_ArrowButton_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_ArrowButton.WBP_ArrowButton_C.SetCornerRadius
// 0x0020 (0x0020 - 0x0000)
struct WBP_ArrowButton_C_SetCornerRadius final
{
public:
	struct FLinearColor                           K2Node_MakeStruct_LinearColor;                     // 0x0000(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_UIKit_Block_BackgroundWithOutline_C* K2Node_DynamicCast_AsWBP_UIKit_Block_Background_with_Outline; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ArrowButton_C_SetCornerRadius) == 0x000008, "Wrong alignment on WBP_ArrowButton_C_SetCornerRadius");
static_assert(sizeof(WBP_ArrowButton_C_SetCornerRadius) == 0x000020, "Wrong size on WBP_ArrowButton_C_SetCornerRadius");
static_assert(offsetof(WBP_ArrowButton_C_SetCornerRadius, K2Node_MakeStruct_LinearColor) == 0x000000, "Member 'WBP_ArrowButton_C_SetCornerRadius::K2Node_MakeStruct_LinearColor' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_SetCornerRadius, K2Node_DynamicCast_AsWBP_UIKit_Block_Background_with_Outline) == 0x000010, "Member 'WBP_ArrowButton_C_SetCornerRadius::K2Node_DynamicCast_AsWBP_UIKit_Block_Background_with_Outline' has a wrong offset!");
static_assert(offsetof(WBP_ArrowButton_C_SetCornerRadius, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_ArrowButton_C_SetCornerRadius::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

