#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Dialog_VM_TextChat_Report

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "FortniteUI_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Dialog_VM_TextChat_Report.WBP_Dialog_VM_TextChat_Report_C
// 0x00C8 (0x0518 - 0x0450)
class UWBP_Dialog_VM_TextChat_Report_C final : public UCommonActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonRichTextBlock*                   Text_ReportSubmitted;                              // 0x0458(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_ErrorMessage;                                 // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_ErrorHeader;                                  // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SB_Mobile;                                         // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonVisibilitySwitcher*              S_ReportContent;                                   // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonVisibilitySwitcher*              S_Content;                                         // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ReportChat_Title;                                  // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   ReportChat_DescriptionText;                        // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_SubmitReport;                                   // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_ReportSubmitted;                                // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_Report;                                         // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_Loading;                                        // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_Error;                                          // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UGridPanel*                             GP_BlockPlayer;                                    // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Dialog_Internal_C*           Dialog_Internal;                                   // 0x04C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTileView*                        CommonTileView;                                    // 0x04D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Loud_C*               Button_SubmitReport;                               // 0x04D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Regular_C*            Button_PlayerBlock;                                // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Regular_C*            Button_Nevermind;                                  // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Loud_C*               Button_CloseError;                                 // 0x04F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Regular_C*            Button_Close_Block;                                // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Loud_C*               Button_Close;                                      // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UIKit_Button_Loud_C*               Button_Block;                                      // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortTextChatReportV3VM*                FortTextChatReportV3VM;                            // 0x0510(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WBP_Dialog_VM_TextChat_Report_Button_Block_K2Node_ComponentBoundEvent_7_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_Button_Close_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_Button_SubmitReport_1_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_Button_SubmitReport_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_CommonTileView_K2Node_ComponentBoundEvent_13_OnListEntryInitializedDynamic__DelegateSignature(class UObject* Item, class UUserWidget* Widget);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_CommonTileView_K2Node_ComponentBoundEvent_4_SimpleListItemEventDynamic__DelegateSignature(class UObject* Item);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_WBP_UIKit_Button_Regular_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_WBP_UIKit_Button_Regular_K2Node_ComponentBoundEvent_5_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BndEvt__WBP_Dialog_VM_TextChat_Report_WBP_UIKit_Button_Regular_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button);
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void ExecuteUbergraph_WBP_Dialog_VM_TextChat_Report(int32 EntryPoint);
	void FillOutBlockPlayers(TArray<class UFortBlockPlayerVM*>& PlayerToBlock);
	void OnInitialized();
	void OnListItemObjectSet(class UObject* ListItemObject);
	struct FEventReply OnMouseWheel(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	class UWidget* OnNavigateDownFromBlockList(EUINavigation Navigation_0);
	void PreConstruct(bool IsDesignTime);
	void SetErrorText(const class FText& Header, const class FText& Message);
	void SetMobileStyle();
	void SetReportableState(ETextReportState ReportState);
	void SetReportChatDescriptionText(const class FText& ChannelType, const class FText& ChannelName);
	void SetReportChatTitle(const class FText& CurrentChannelName);
	void SetReportSubmittedID(const class FString& ReportId);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Dialog_VM_TextChat_Report_C">();
	}
	static class UWBP_Dialog_VM_TextChat_Report_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Dialog_VM_TextChat_Report_C>();
	}
};
static_assert(alignof(UWBP_Dialog_VM_TextChat_Report_C) == 0x000008, "Wrong alignment on UWBP_Dialog_VM_TextChat_Report_C");
static_assert(sizeof(UWBP_Dialog_VM_TextChat_Report_C) == 0x000518, "Wrong size on UWBP_Dialog_VM_TextChat_Report_C");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, UberGraphFrame) == 0x000450, "Member 'UWBP_Dialog_VM_TextChat_Report_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Text_ReportSubmitted) == 0x000458, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Text_ReportSubmitted' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Text_ErrorMessage) == 0x000460, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Text_ErrorMessage' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Text_ErrorHeader) == 0x000468, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Text_ErrorHeader' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, SB_Mobile) == 0x000470, "Member 'UWBP_Dialog_VM_TextChat_Report_C::SB_Mobile' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, S_ReportContent) == 0x000478, "Member 'UWBP_Dialog_VM_TextChat_Report_C::S_ReportContent' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, S_Content) == 0x000480, "Member 'UWBP_Dialog_VM_TextChat_Report_C::S_Content' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, ReportChat_Title) == 0x000488, "Member 'UWBP_Dialog_VM_TextChat_Report_C::ReportChat_Title' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, ReportChat_DescriptionText) == 0x000490, "Member 'UWBP_Dialog_VM_TextChat_Report_C::ReportChat_DescriptionText' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_SubmitReport) == 0x000498, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_SubmitReport' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_ReportSubmitted) == 0x0004A0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_ReportSubmitted' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_Report) == 0x0004A8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_Report' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_Loading) == 0x0004B0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_Loading' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_Error) == 0x0004B8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_Error' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, GP_BlockPlayer) == 0x0004C0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::GP_BlockPlayer' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Dialog_Internal) == 0x0004C8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Dialog_Internal' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, CommonTileView) == 0x0004D0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::CommonTileView' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_SubmitReport) == 0x0004D8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_SubmitReport' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_PlayerBlock) == 0x0004E0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_PlayerBlock' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_Nevermind) == 0x0004E8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_Nevermind' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_CloseError) == 0x0004F0, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_CloseError' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_Close_Block) == 0x0004F8, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_Close_Block' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_Close) == 0x000500, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_Close' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, Button_Block) == 0x000508, "Member 'UWBP_Dialog_VM_TextChat_Report_C::Button_Block' has a wrong offset!");
static_assert(offsetof(UWBP_Dialog_VM_TextChat_Report_C, FortTextChatReportV3VM) == 0x000510, "Member 'UWBP_Dialog_VM_TextChat_Report_C::FortTextChatReportV3VM' has a wrong offset!");

}

