#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Nameplate_ShopIcon

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Nameplate_ShopIcon.WBP_Nameplate_ShopIcon_C
// 0x0028 (0x0320 - 0x02F8)
class UWBP_Nameplate_ShopIcon_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ShopIcon;                                          // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 GraphicBolt;                                       // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Background;                                        // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x0318(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void SetMobileStyle();
	void PreConstruct(bool IsDesignTime);
	void PlayIntroAnimation();
	void ExecuteUbergraph_WBP_Nameplate_ShopIcon(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Nameplate_ShopIcon_C">();
	}
	static class UWBP_Nameplate_ShopIcon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Nameplate_ShopIcon_C>();
	}
};
static_assert(alignof(UWBP_Nameplate_ShopIcon_C) == 0x000008, "Wrong alignment on UWBP_Nameplate_ShopIcon_C");
static_assert(sizeof(UWBP_Nameplate_ShopIcon_C) == 0x000320, "Wrong size on UWBP_Nameplate_ShopIcon_C");
static_assert(offsetof(UWBP_Nameplate_ShopIcon_C, UberGraphFrame) == 0x0002F8, "Member 'UWBP_Nameplate_ShopIcon_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Nameplate_ShopIcon_C, ShopIcon) == 0x000300, "Member 'UWBP_Nameplate_ShopIcon_C::ShopIcon' has a wrong offset!");
static_assert(offsetof(UWBP_Nameplate_ShopIcon_C, GraphicBolt) == 0x000308, "Member 'UWBP_Nameplate_ShopIcon_C::GraphicBolt' has a wrong offset!");
static_assert(offsetof(UWBP_Nameplate_ShopIcon_C, Background) == 0x000310, "Member 'UWBP_Nameplate_ShopIcon_C::Background' has a wrong offset!");
static_assert(offsetof(UWBP_Nameplate_ShopIcon_C, Intro) == 0x000318, "Member 'UWBP_Nameplate_ShopIcon_C::Intro' has a wrong offset!");

}

