#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TournamentDetailsSectionItem_Scoring

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.AddPlaceIcon
// 0x0010 (0x0010 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon final
{
public:
	class UImage*                                 CallFunc_SpawnObject_ReturnValue;                  // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UGridSlot*                              CallFunc_AddChildToGrid_ReturnValue;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon) == 0x000010, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon, CallFunc_SpawnObject_ReturnValue) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon, CallFunc_AddChildToGrid_ReturnValue) == 0x000008, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceIcon::CallFunc_AddChildToGrid_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.AddPlaceText
// 0x0028 (0x0028 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText final
{
public:
	class UCommonTextBlock*                       CallFunc_SpawnObject_ReturnValue;                  // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FGameplayTag>                   K2Node_MakeArray_Array;                            // 0x0008(0x0010)(ReferenceParm)
	bool                                          CallFunc_UpdateWidgetStyleTags_ReturnValue;        // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGridSlot*                              CallFunc_AddChildToGrid_ReturnValue;               // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText) == 0x000028, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText, CallFunc_SpawnObject_ReturnValue) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText, K2Node_MakeArray_Array) == 0x000008, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText, CallFunc_UpdateWidgetStyleTags_ReturnValue) == 0x000018, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText::CallFunc_UpdateWidgetStyleTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText, CallFunc_AddChildToGrid_ReturnValue) == 0x000020, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_AddPlaceText::CallFunc_AddChildToGrid_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring
// 0x0008 (0x0008 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring) == 0x000004, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring) == 0x000008, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring, EntryPoint) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring, K2Node_Event_IsDesignTime) == 0x000004, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_ExecuteUbergraph_WBP_TournamentDetailsSectionItem_Scoring::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct) == 0x000001, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.RemovePlaceImage
// 0x0001 (0x0001 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage) == 0x000001, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage) == 0x000001, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceImage::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.RemovePlaceText
// 0x0001 (0x0001 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText) == 0x000001, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText) == 0x000001, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_RemovePlaceText::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.Set Prize Data
// 0x0020 (0x0020 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data final
{
public:
	class FText                                   In_Threshold_Text;                                 // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   In_Value_Text;                                     // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data) == 0x000020, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data, In_Threshold_Text) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data::In_Threshold_Text' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data, In_Value_Text) == 0x000010, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_Set_Prize_Data::In_Value_Text' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetPlace
// 0x0018 (0x0018 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace) == 0x000018, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace, InText) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace::InText' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPlace::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetPlaceSlotSettings
// 0x0008 (0x0008 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings final
{
public:
	class UGridSlot*                              Grid_Slot;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings) == 0x000008, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings, Grid_Slot) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPlaceSlotSettings::Grid_Slot' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetPoints
// 0x0018 (0x0018 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints final
{
public:
	int32                                         Points;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0010)()
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints) == 0x000018, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints, Points) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints::Points' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints, CallFunc_Conv_IntToText_ReturnValue) == 0x000008, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPoints::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetPointsFloat
// 0x0080 (0x0080 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat final
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0008(0x0010)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0018(0x0048)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0060(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0070(0x0010)()
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat) == 0x000080, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat, Value) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat::Value' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat, CallFunc_Conv_DoubleToText_ReturnValue) == 0x000008, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat::CallFunc_Conv_DoubleToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat, K2Node_MakeStruct_FormatArgumentData) == 0x000018, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat, K2Node_MakeArray_Array) == 0x000060, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat, CallFunc_Format_ReturnValue) == 0x000070, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsFloat::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetPointsText
// 0x0010 (0x0010 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText final
{
public:
	class FText                                   PointsText_0;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText) == 0x000010, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText, PointsText_0) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetPointsText::PointsText_0' has a wrong offset!");

// Function WBP_TournamentDetailsSectionItem_Scoring.WBP_TournamentDetailsSectionItem_Scoring_C.SetVM_TournamentDetailsSectionItem_PrizeDebug
// 0x0028 (0x0028 - 0x0000)
struct WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug final
{
public:
	class UVM_TournamentDetailsSectionItem_PrizeDebug_C* ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;         // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug) == 0x000008, "Wrong alignment on WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug");
static_assert(sizeof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug) == 0x000028, "Wrong size on WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug, ViewModel) == 0x000000, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug::ViewModel' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug, CallFunc_GetExtension_ReturnValue) == 0x000008, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug::CallFunc_GetExtension_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug, CallFunc_SetViewModel_ViewModel_CastInput) == 0x000010, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug::CallFunc_SetViewModel_ViewModel_CastInput' has a wrong offset!");
static_assert(offsetof(WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug, CallFunc_SetViewModel_ReturnValue) == 0x000020, "Member 'WBP_TournamentDetailsSectionItem_Scoring_C_SetVM_TournamentDetailsSectionItem_PrizeDebug::CallFunc_SetViewModel_ReturnValue' has a wrong offset!");

}

