#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TextChat_Button_MoreOptions

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_UIKit_Button_Generic_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_TextChat_Button_MoreOptions.WBP_TextChat_Button_MoreOptions_C
// 0x0010 (0x18E0 - 0x18D0)
class UWBP_TextChat_Button_MoreOptions_C final : public UWBP_UIKit_Button_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_TextChat_Button_MoreOptions_C;  // 0x18D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_UIKit_Block_Outline_C*             WBP_UIKit_Block_Outline;                           // 0x18D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnHovered();
	void BP_OnUnhovered();
	void Construct();
	void ExecuteUbergraph_WBP_TextChat_Button_MoreOptions(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_TextChat_Button_MoreOptions_C">();
	}
	static class UWBP_TextChat_Button_MoreOptions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_TextChat_Button_MoreOptions_C>();
	}
};
static_assert(alignof(UWBP_TextChat_Button_MoreOptions_C) == 0x000010, "Wrong alignment on UWBP_TextChat_Button_MoreOptions_C");
static_assert(sizeof(UWBP_TextChat_Button_MoreOptions_C) == 0x0018E0, "Wrong size on UWBP_TextChat_Button_MoreOptions_C");
static_assert(offsetof(UWBP_TextChat_Button_MoreOptions_C, UberGraphFrame_WBP_TextChat_Button_MoreOptions_C) == 0x0018D0, "Member 'UWBP_TextChat_Button_MoreOptions_C::UberGraphFrame_WBP_TextChat_Button_MoreOptions_C' has a wrong offset!");
static_assert(offsetof(UWBP_TextChat_Button_MoreOptions_C, WBP_UIKit_Block_Outline) == 0x0018D8, "Member 'UWBP_TextChat_Button_MoreOptions_C::WBP_UIKit_Block_Outline' has a wrong offset!");

}

