#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuestCategoryRow_Entry

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.BindButtonEvents
// 0x0038 (0x0038 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_BindButtonEvents final
{
public:
	class UCommonButtonBase*                      ButtonInstance;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Bind;                                              // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UCommonButtonBase* Button)> K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UCommonButtonBase* Button)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x001C(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UCommonButtonBase* Button)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0028(0x000C)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_BindButtonEvents");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents) == 0x000038, "Wrong size on WBP_QuestCategoryRow_Entry_C_BindButtonEvents");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, ButtonInstance) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::ButtonInstance' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, Bind) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::Bind' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, K2Node_CreateDelegate_OutputDelegate_1) == 0x00001C, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BindButtonEvents, K2Node_CreateDelegate_OutputDelegate_2) == 0x000028, "Member 'WBP_QuestCategoryRow_Entry_C_BindButtonEvents::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.ClearAllEntries
// 0x0040 (0x0040 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_ClearAllEntries final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetAllEntries_ReturnValue;                // 0x0008(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_DynamicCast_AsCommon_Button_Base;           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_ClearAllEntries");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries) == 0x000040, "Wrong size on WBP_QuestCategoryRow_Entry_C_ClearAllEntries");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, CallFunc_GetAllEntries_ReturnValue) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::CallFunc_GetAllEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, CallFunc_Array_Get_Item) == 0x000020, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, K2Node_DynamicCast_AsCommon_Button_Base) == 0x000028, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::K2Node_DynamicCast_AsCommon_Button_Base' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, CallFunc_Array_Length_ReturnValue) == 0x000034, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ClearAllEntries, CallFunc_Less_IntInt_ReturnValue) == 0x000038, "Member 'WBP_QuestCategoryRow_Entry_C_ClearAllEntries::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.ExecuteUbergraph_WBP_QuestCategoryRow_Entry
// 0x0020 (0x0020 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UQuestUICategoryRowVM*                  K2Node_DynamicCast_AsQuest_UI_Category_Row_View_Model; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected;                          // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry) == 0x000020, "Wrong size on WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, EntryPoint) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, K2Node_Event_ListItemObject) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, K2Node_DynamicCast_AsQuest_UI_Category_Row_View_Model) == 0x000010, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::K2Node_DynamicCast_AsQuest_UI_Category_Row_View_Model' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, K2Node_Event_bIsExpanded) == 0x000019, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::K2Node_Event_bIsExpanded' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry, K2Node_Event_bIsSelected) == 0x00001A, "Member 'WBP_QuestCategoryRow_Entry_C_ExecuteUbergraph_WBP_QuestCategoryRow_Entry::K2Node_Event_bIsSelected' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.HandleButtonClicked
// 0x0028 (0x0028 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_HandleButtonClicked final
{
public:
	class UCommonButtonBase*                      ButtonInstance;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UObject*                                CallFunc_GetListItemObject_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UListViewBase*                          CallFunc_GetOwningListView_ReturnValue;            // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonListView*                        K2Node_DynamicCast_AsCommon_List_View;             // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_HandleButtonClicked");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked) == 0x000028, "Wrong size on WBP_QuestCategoryRow_Entry_C_HandleButtonClicked");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked, ButtonInstance) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonClicked::ButtonInstance' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked, CallFunc_GetListItemObject_ReturnValue) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonClicked::CallFunc_GetListItemObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked, CallFunc_GetOwningListView_ReturnValue) == 0x000010, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonClicked::CallFunc_GetOwningListView_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked, K2Node_DynamicCast_AsCommon_List_View) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonClicked::K2Node_DynamicCast_AsCommon_List_View' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonClicked, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonClicked::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.HandleButtonFocused
// 0x0028 (0x0028 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_HandleButtonFocused final
{
public:
	class UCommonButtonBase*                      ButtonInstance;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UUserWidget*>                    CallFunc_GetAllEntries_ReturnValue;                // 0x0008(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Find_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_HandleButtonFocused");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused) == 0x000028, "Wrong size on WBP_QuestCategoryRow_Entry_C_HandleButtonFocused");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused, ButtonInstance) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonFocused::ButtonInstance' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused, CallFunc_GetAllEntries_ReturnValue) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonFocused::CallFunc_GetAllEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused, CallFunc_Array_Find_ReturnValue) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonFocused::CallFunc_Array_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonFocused::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonFocused, CallFunc_Greater_IntInt_ReturnValue) == 0x000020, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonFocused::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.HandleButtonHovered
// 0x0008 (0x0008 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_HandleButtonHovered final
{
public:
	class UCommonButtonBase*                      ButtonInstance;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_HandleButtonHovered) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_HandleButtonHovered");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_HandleButtonHovered) == 0x000008, "Wrong size on WBP_QuestCategoryRow_Entry_C_HandleButtonHovered");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_HandleButtonHovered, ButtonInstance) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_HandleButtonHovered::ButtonInstance' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.OnFocusReceived
// 0x01D8 (0x01D8 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            K2Node_MakeStruct_EventReply;                      // 0x00F8(0x00B8)()
	TArray<class UUserWidget*>                    CallFunc_GetAllEntries_ReturnValue;                // 0x01B0(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_Array_Get_Item;                           // 0x01D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_OnFocusReceived");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived) == 0x0001D8, "Wrong size on WBP_QuestCategoryRow_Entry_C_OnFocusReceived");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, InFocusEvent) == 0x000038, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, ReturnValue) == 0x000040, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, K2Node_MakeStruct_EventReply) == 0x0000F8, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::K2Node_MakeStruct_EventReply' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_GetAllEntries_ReturnValue) == 0x0001B0, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_GetAllEntries_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_Array_Length_ReturnValue) == 0x0001C0, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_Greater_IntInt_ReturnValue) == 0x0001C4, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_Subtract_IntInt_ReturnValue) == 0x0001C8, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_Clamp_ReturnValue) == 0x0001CC, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_Clamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnFocusReceived, CallFunc_Array_Get_Item) == 0x0001D0, "Member 'WBP_QuestCategoryRow_Entry_C_OnFocusReceived::CallFunc_Array_Get_Item' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet) == 0x000008, "Wrong size on WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.SetActiveColumn
// 0x0004 (0x0004 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_SetActiveColumn final
{
public:
	int32                                         Column;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_SetActiveColumn) == 0x000004, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_SetActiveColumn");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_SetActiveColumn) == 0x000004, "Wrong size on WBP_QuestCategoryRow_Entry_C_SetActiveColumn");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetActiveColumn, Column) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_SetActiveColumn::Column' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.SetCategoryInterfaceVMs
// 0x0060 (0x0060 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs final
{
public:
	TArray<class UQuestUICategoryInterfaceVM*>    CategoryInterfaceVMs;                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UQuestUICategoryInterfaceVM*            CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UQuestUICollectionsVM*                  K2Node_DynamicCast_AsQuest_UI_Collections_View_Model; // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UQuestUICategoryVM*                     K2Node_DynamicCast_AsQuest_UI_Category_View_Model; // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CollectionsButton_Entry_C*         CallFunc_BP_CreateEntryOfClass_ReturnValue;        // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_QuestCategoryTile_C*               CallFunc_BP_CreateEntryOfClass_ReturnValue_1;      // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs) == 0x000060, "Wrong size on WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CategoryInterfaceVMs) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CategoryInterfaceVMs' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, Temp_int_Array_Index_Variable) == 0x000018, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Array_Get_Item) == 0x000020, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, K2Node_DynamicCast_AsQuest_UI_Collections_View_Model) == 0x000028, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::K2Node_DynamicCast_AsQuest_UI_Collections_View_Model' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, K2Node_DynamicCast_AsQuest_UI_Category_View_Model) == 0x000038, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::K2Node_DynamicCast_AsQuest_UI_Category_View_Model' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, K2Node_DynamicCast_bSuccess_1) == 0x000040, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Add_IntInt_ReturnValue) == 0x000044, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Array_Length_ReturnValue_1) == 0x000048, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_Greater_IntInt_ReturnValue) == 0x00004C, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_BP_CreateEntryOfClass_ReturnValue) == 0x000050, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_BP_CreateEntryOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs, CallFunc_BP_CreateEntryOfClass_ReturnValue_1) == 0x000058, "Member 'WBP_QuestCategoryRow_Entry_C_SetCategoryInterfaceVMs::CallFunc_BP_CreateEntryOfClass_ReturnValue_1' has a wrong offset!");

// Function WBP_QuestCategoryRow_Entry.WBP_QuestCategoryRow_Entry_C.SetQuestUICategoryRowVM
// 0x0028 (0x0028 - 0x0000)
struct WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM final
{
public:
	class UQuestUICategoryRowVM*                  ViewModel;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UMVVMView*                              CallFunc_GetExtension_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class INotifyFieldValueChanged> CallFunc_SetViewModel_ViewModel_CastInput;         // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_SetViewModel_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM) == 0x000008, "Wrong alignment on WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM");
static_assert(sizeof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM) == 0x000028, "Wrong size on WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM, ViewModel) == 0x000000, "Member 'WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM::ViewModel' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM, CallFunc_GetExtension_ReturnValue) == 0x000008, "Member 'WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM::CallFunc_GetExtension_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM, CallFunc_SetViewModel_ViewModel_CastInput) == 0x000010, "Member 'WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM::CallFunc_SetViewModel_ViewModel_CastInput' has a wrong offset!");
static_assert(offsetof(WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM, CallFunc_SetViewModel_ReturnValue) == 0x000020, "Member 'WBP_QuestCategoryRow_Entry_C_SetQuestUICategoryRowVM::CallFunc_SetViewModel_ReturnValue' has a wrong offset!");

}

